export const CSS_PROPERTY_VALUES = {
  "display": ["block", "inline", "inline-block", "flex", "inline-flex", "grid", "inline-grid", "none", "contents", "table", "list-item"],
  "position": ["static", "relative", "absolute", "fixed", "sticky"],
  "flex-direction": ["row", "row-reverse", "column", "column-reverse"],
  "flex-wrap": ["nowrap", "wrap", "wrap-reverse"],
  "justify-content": ["flex-start", "flex-end", "center", "space-between", "space-around", "space-evenly", "start", "end"],
  "align-items": ["flex-start", "flex-end", "center", "baseline", "stretch", "start", "end"],
  "align-self": ["auto", "flex-start", "flex-end", "center", "baseline", "stretch"],
  "align-content": ["flex-start", "flex-end", "center", "space-between", "space-around", "stretch"],
  "text-align": ["left", "right", "center", "justify", "start", "end"],
  "text-decoration": ["none", "underline", "overline", "line-through", "underline dotted", "underline wavy"],
  "text-transform": ["none", "uppercase", "lowercase", "capitalize"],
  "white-space": ["normal", "nowrap", "pre", "pre-wrap", "pre-line", "break-spaces"],
  "overflow": ["visible", "hidden", "scroll", "auto", "clip"],
  "overflow-x": ["visible", "hidden", "scroll", "auto", "clip"],
  "overflow-y": ["visible", "hidden", "scroll", "auto", "clip"],
  "visibility": ["visible", "hidden", "collapse"],
  "font-style": ["normal", "italic", "oblique"],
  "font-weight": ["normal", "bold", "bolder", "lighter", "100", "200", "300", "400", "500", "600", "700", "800", "900"],
  "font-variant": ["normal", "small-caps"],
  "cursor": ["default", "pointer", "text", "move", "grab", "grabbing", "crosshair", "help", "wait", "not-allowed", "zoom-in", "zoom-out"],
  "box-sizing": ["content-box", "border-box"],
  "float": ["none", "left", "right"],
  "clear": ["none", "left", "right", "both"],
  "resize": ["none", "both", "horizontal", "vertical"],
  "object-fit": ["fill", "contain", "cover", "none", "scale-down"],
  "pointer-events": ["auto", "none"],
  "user-select": ["auto", "none", "text", "all"],
  "touch-action": ["auto", "none", "manipulation", "pan-x", "pan-y", "pan-x pan-y", "pinch-zoom"],
  "list-style": ["none", "disc", "circle", "square", "decimal", "lower-alpha", "upper-alpha", "lower-roman", "upper-roman"],
  "list-style-type": ["none", "disc", "circle", "square", "decimal", "lower-alpha", "upper-alpha", "lower-roman", "upper-roman"],
  "background-repeat": ["repeat", "no-repeat", "repeat-x", "repeat-y", "space", "round"],
  "background-size": ["auto", "cover", "contain"],
  "background-attachment": ["scroll", "fixed", "local"],
  "background-position": ["center", "top", "bottom", "left", "right", "top left", "top right", "bottom left", "bottom right"],
  "background-clip": ["border-box", "padding-box", "content-box", "text"],
  "text-overflow": ["clip", "ellipsis"],
  "word-break": ["normal", "break-all", "keep-all", "break-word"],
  "overflow-wrap": ["normal", "break-word", "anywhere"],
  "grid-auto-flow": ["row", "column", "dense", "row dense", "column dense"],
  "justify-items": ["start", "end", "center", "stretch"],
  "place-items": ["start", "end", "center", "stretch"],
  "place-content": ["start", "end", "center", "space-between", "space-around", "space-evenly", "stretch"],
  "gap": ["0", "4px", "8px", "12px", "16px", "20px", "24px", "32px"],
  "border-style": ["none", "solid", "dashed", "dotted", "double", "groove", "ridge", "inset", "outset"],
  "border-radius": ["0", "4px", "8px", "12px", "16px", "50%", "999px"],
  "outline-style": ["none", "solid", "dashed", "dotted", "double"],
  "mix-blend-mode": ["normal", "multiply", "screen", "overlay", "darken", "lighten", "color-dodge", "color-burn", "hard-light", "soft-light", "difference", "exclusion", "hue", "saturation", "color", "luminosity"],
  "transform-origin": ["center", "top", "bottom", "left", "right", "top left", "top right", "bottom left", "bottom right"],
  "transition-timing-function": ["ease", "linear", "ease-in", "ease-out", "ease-in-out", "step-start", "step-end", "cubic-bezier"],
  "animation-timing-function": ["ease", "linear", "ease-in", "ease-out", "ease-in-out", "step-start", "step-end", "cubic-bezier"],
  "animation-direction": ["normal", "reverse", "alternate", "alternate-reverse"],
  "animation-fill-mode": ["none", "forwards", "backwards", "both"],
  "animation-play-state": ["running", "paused"],
};

export const CSS_AT_RULES = [
  "media", "supports", "keyframes", "font-face", "import",
  "charset", "namespace", "page", "layer", "container", "property",
];

export const CSS_PSEUDO = [
  ":hover", ":focus", ":active", ":visited", ":link",
  ":first-child", ":last-child", ":nth-child", ":not",
  ":before", ":after", ":placeholder", ":disabled", ":checked",
  "::before", "::after", "::placeholder", "::selection",
  "::first-line", "::first-letter",
];