window.LimnTemplates = {

  dressup: {
    name: "Dress-Up",
    fields: [
      { key: "title",      label: "Title",      type: "text",  default: "My Outfit" },
      { key: "bg",         label: "Background", type: "color", default: "#0d0d2a" },
      { key: "hatColor",   label: "Hat",        type: "color", default: "#4af" },
      { key: "headColor",  label: "Head",       type: "color", default: "#fd3" },
      { key: "shirtColor", label: "Shirt",      type: "color", default: "#f44" },
      { key: "pantsColor", label: "Pants",      type: "color", default: "#c4f" },
      { key: "shoesColor", label: "Shoes",      type: "color", default: "#111" }
    ],
    config: function(cfg) {
      return {
        title: cfg.title,
        world: { w: 800, h: 600, bg: cfg.bg },
        slots: [
          { x: 355, y: 140, w: 90,  h: 30,  color: cfg.hatColor },
          { x: 360, y: 170, w: 80,  h: 80,  color: cfg.headColor },
          { x: 350, y: 250, w: 100, h: 120, color: cfg.shirtColor },
          { x: 355, y: 370, w: 90,  h: 90,  color: cfg.pantsColor },
          { x: 350, y: 460, w: 100, h: 30,  color: cfg.shoesColor }
        ],
        palette: [cfg.hatColor, cfg.headColor, cfg.shirtColor,
                  cfg.pantsColor, cfg.shoesColor, "#ffffff", "#111111"]
      };
    },
    generate: function(cfg) {
      var slots = [
        { x: 355, y: 140, w: 90,  h: 30,  color: cfg.hatColor },
        { x: 360, y: 170, w: 80,  h: 80,  color: cfg.headColor },
        { x: 350, y: 250, w: 100, h: 120, color: cfg.shirtColor },
        { x: 355, y: 370, w: 90,  h: 90,  color: cfg.pantsColor },
        { x: 350, y: 460, w: 100, h: 30,  color: cfg.shoesColor }
      ];
      var palette = [cfg.hatColor, cfg.headColor, cfg.shirtColor,
                     cfg.pantsColor, cfg.shoesColor, "#ffffff", "#111111"];
      return [
        "const display = new Display();",
        "display.perform();",
        "display.start(800, 600);",
        "display.backgroundColor('" + cfg.bg + "');",
        "",
        "const slots = " + JSON.stringify(slots) + ";",
        "const palette = " + JSON.stringify(palette) + ";",
        "",
        "const parts = slots.map((s, i) => {",
        "  const c = new Component(s.w, s.h, s.color, s.x, s.y, 'rect');",
        "  display.add(c);",
        "  c.slotIndex = i;",
        "  return c;",
        "});",
        "",
        "let mouseWasDown = false;",
        "",
        "function update(dt) {",
        "  if (display.x !== false && !mouseWasDown) {",
        "    const mx = display.x, my = display.y;",
        "    for (const p of parts) {",
        "      if (mx >= p.x && mx <= p.x + p.width && my >= p.y && my <= p.y + p.height) {",
        "        const cur = palette.indexOf(p.color);",
        "        p.color = palette[(cur + 1) % palette.length];",
        "        break;",
        "      }",
        "    }",
        "    mouseWasDown = true;",
        "  }",
        "  if (display.x === false) mouseWasDown = false;",
        "}"
      ].join("\n");
    }
  },

  platformer: {
    name: "Platformer",
    fields: [
      { key: "title",     label: "Title",           type: "text",  default: "Jump Quest" },
      { key: "bg",        label: "Sky",             type: "color", default: "#0d0d2a" },
      { key: "ground",    label: "Ground",          type: "color", default: "#4f8" },
      { key: "player",    label: "Player",          type: "color", default: "#4af" },
      { key: "coin",      label: "Coin",            type: "color", default: "#fd3" },
      { key: "speed",     label: "Speed (100-500)", type: "text",  default: "280" },
      { key: "jumpForce", label: "Jump (8-20)",     type: "text",  default: "13" },
      { key: "coins",     label: "Number of coins", type: "text",  default: "5" }
    ],
    config: function(cfg) {
      return {
        title: cfg.title,
        world: { w: 800, h: 600, bg: cfg.bg },
        slots: [
          { x: 100, y: 500, w: 40, h: 40, color: cfg.player },
          { x: 240, y: 380, w: 24, h: 24, color: cfg.coin }
        ],
        palette: [cfg.player, cfg.coin, cfg.ground]
      };
    },
    generate: function(cfg) {
      var speed = parseInt(cfg.speed) || 280;
      var jump = parseInt(cfg.jumpForce) || 13;
      var count = parseInt(cfg.coins) || 5;

      var coinPositions = [];
      var seed = 42;
      for (var i = 0; i < count; i++) {
        seed = (seed * 9301 + 49297) % 233280;
        var rnd = seed / 233280;
        var x = 120 + Math.floor(rnd * 580);
        var y = 380 - (i % 3) * 80;
        coinPositions.push({ x: x, y: y });
      }

      return [
        "const display = new Display();",
        "display.perform();",
        "display.start(800, 600);",
        "display.backgroundColor('" + cfg.bg + "');",
        "",
        "const player = new Component(40, 40, '" + cfg.player + "', 100, 400, 'rect');",
        "display.add(player);",
        "",
        "const ground = new Component(800, 60, '" + cfg.ground + "', 0, 540, 'rect');",
        "display.add(ground);",
        "",
        "const platforms = [",
        "  new Component(150, 20, '" + cfg.ground + "', 200, 460, 'rect'),",
        "  new Component(150, 20, '" + cfg.ground + "', 450, 380, 'rect'),",
        "  new Component(150, 20, '" + cfg.ground + "', 650, 300, 'rect')",
        "];",
        "platforms.forEach(function(p) { display.add(p); });",
        "",
        "const coinPositions = " + JSON.stringify(coinPositions) + ";",
        "const coins = coinPositions.map(function(c) {",
        "  var coin = new Component(24, 24, '" + cfg.coin + "', c.x, c.y, 'rect');",
        "  display.add(coin);",
        "  return coin;",
        "});",
        "",
        "const score = new Tctxt('20px','Arial','white',20,40,'left',false,'top','rgba(0,0,0,0.5)',10,4);",
        "score.setText('Score: 0');",
        "display.add(score);",
        "",
        "const BTN = 80;",
        "const BTN_Y = 500;",
        "function mkBtn(x, color) {",
        "  return new Component(BTN, BTN, color, x, BTN_Y, 'rect');",
        "}",
        "const btnL = mkBtn(20,  '#1a1a2e');",
        "const btnR = mkBtn(120, '#1a1a2e');",
        "const btnJ = mkBtn(680, '#2563eb');",
        "const lblL = new Tctxt('36px','Arial','white',60,540,'center',false,'middle');",
        "const lblR = new Tctxt('36px','Arial','white',160,540,'center',false,'middle');",
        "const lblJ = new Tctxt('16px','Arial','white',720,540,'center',false,'middle');",
        "lblL.setText('◀'); lblR.setText('▶'); lblJ.setText('JUMP');",
        "display.add(btnL); display.add(btnR); display.add(btnJ);",
        "display.add(lblL); display.add(lblR); display.add(lblJ);",
        "",
        "function inBtn(b, x, y) {",
        "  return x >= b.x && x <= b.x + b.width && y >= b.y && y <= b.y + b.height;",
        "}",
        "",
        "let vy = 0;",
        "let onGround = false;",
        "let points = 0;",
        "let won = false;",
        "",
        "function rectHit(a, b) {",
        "  return a.x < b.x + b.width && a.x + a.width > b.x && a.y < b.y + b.height && a.y + a.height > b.y;",
        "}",
        "",
        "function update(dt) {",
        "  if (won) return;",
        "  const sp = " + speed + ";",
        "  const jf = " + jump + ";",
        "",
        "  const mx = display.x, my = display.y;",
        "  const touchingL = mx !== false && inBtn(btnL, mx, my);",
        "  const touchingR = mx !== false && inBtn(btnR, mx, my);",
        "  const touchingJ = mx !== false && inBtn(btnJ, mx, my);",
        "",
        "  if (display.keys[37] || display.keys[65] || touchingL) player.x -= sp * dt;",
        "  if (display.keys[39] || display.keys[68] || touchingR) player.x += sp * dt;",
        "",
        "  const keyJump = display.keys[38] || display.keys[32] || display.keys[87];",
        "  if ((keyJump || touchingJ) && onGround) {",
        "    vy = -jf;",
        "    onGround = false;",
        "  }",
        "",
        "  vy += 40 * dt;",
        "  player.y += vy;",
        "  onGround = false;",
        "",
        "  if (rectHit(player, ground)) {",
        "    player.y = ground.y - player.height;",
        "    vy = 0;",
        "    onGround = true;",
        "  }",
        "",
        "  for (const p of platforms) {",
        "    if (rectHit(player, p) && player.y + player.height - vy <= p.y + 4) {",
        "      player.y = p.y - player.height;",
        "      vy = 0;",
        "      onGround = true;",
        "    }",
        "  }",
        "",
        "  if (player.x < 0) player.x = 0;",
        "  if (player.x + player.width > 800) player.x = 800 - player.width;",
        "",
        "  for (let i = coins.length - 1; i >= 0; i--) {",
        "    if (rectHit(player, coins[i])) {",
        "      coins[i].destroy();",
        "      coins.splice(i, 1);",
        "      points += 10;",
        "      score.setText('Score: ' + points);",
        "    }",
        "  }",
        "",
        "  if (coins.length === 0 && !won) {",
        "    won = true;",
        "    score.setText('You win! Score: ' + points);",
        "  }",
        "}"
      ].join("\n");
    }
  },

  runner: {
    name: "Runner",
    fields: [
      { key: "title",    label: "Title",               type: "text",  default: "Speed Run" },
      { key: "bg",       label: "Sky",                 type: "color", default: "#1a1a3a" },
      { key: "ground",   label: "Ground",              type: "color", default: "#333333" },
      { key: "player",   label: "Player",              type: "color", default: "#4af" },
      { key: "obstacle", label: "Obstacle",            type: "color", default: "#f44" },
      { key: "speed",    label: "Scroll speed (1-20)", type: "text",  default: "6" },
      { key: "spawn",    label: "Spawn rate",          type: "text",  default: "100" }
    ],
    config: function(cfg) {
      return {
        title: cfg.title,
        world: { w: 800, h: 600, bg: cfg.bg },
        slots: [
          { x: 100, y: 500, w: 40, h: 40, color: cfg.player },
          { x: 700, y: 480, w: 40, h: 60, color: cfg.obstacle }
        ],
        palette: [cfg.player, cfg.obstacle, cfg.ground]
      };
    },
    generate: function(cfg) {
      var speed = parseInt(cfg.speed) || 6;
      var spawnRate = parseInt(cfg.spawn) || 100;
      return [
        "const display = new Display();",
        "display.perform();",
        "display.start(800, 600);",
        "display.backgroundColor('" + cfg.bg + "');",
        "",
        "const ground = new Component(800, 60, '" + cfg.ground + "', 0, 540, 'rect');",
        "display.add(ground);",
        "",
        "const player = new Component(40, 40, '" + cfg.player + "', 100, 500, 'rect');",
        "display.add(player);",
        "",
        "const score = new Tctxt('20px','Arial','white',20,40,'left',false,'top','rgba(0,0,0,0.5)',10,4);",
        "score.setText('Tap to jump. Score: 0');",
        "display.add(score);",
        "",
        "let restartBtn = null;",
        "let restartLbl = null;",
        "",
        "const obstacles = [];",
        "let frame = 0;",
        "let vy = 0;",
        "let onGround = true;",
        "let points = 0;",
        "let gameOver = false;",
        "",
        "function rectHit(a, b) {",
        "  return a.x < b.x + b.width && a.x + a.width > b.x && a.y < b.y + b.height && a.y + a.height > b.y;",
        "}",
        "",
        "function spawn() {",
        "  const h = 40 + Math.floor(Math.random() * 40);",
        "  const o = new Component(40, h, '" + cfg.obstacle + "', 820, 540 - h, 'rect');",
        "  display.add(o);",
        "  obstacles.push(o);",
        "}",
        "",
        "function showRestart() {",
        "  restartBtn = new Component(200, 60, '#2563eb', 300, 300, 'rect');",
        "  restartLbl = new Tctxt('24px','Arial','white',400,330,'center',false,'middle');",
        "  restartLbl.setText('▶ PLAY AGAIN');",
        "  display.add(restartBtn); display.add(restartLbl);",
        "}",
        "",
        "function restart() {",
        "  if (restartBtn) { restartBtn.destroy(); restartBtn = null; }",
        "  if (restartLbl) { restartLbl.destroy(); restartLbl = null; }",
        "  for (let i = obstacles.length - 1; i >= 0; i--) {",
        "    obstacles[i].destroy();",
        "  }",
        "  obstacles.length = 0;",
        "  player.x = 100; player.y = 500;",
        "  vy = 0; onGround = true; points = 0; frame = 0;",
        "  gameOver = false;",
        "  score.setText('Tap to jump. Score: 0');",
        "}",
        "",
        "function update(dt) {",
        "  if (gameOver) {",
        "    const mx = display.x, my = display.y;",
        "    if (mx !== false && restartBtn &&",
        "        mx >= restartBtn.x && mx <= restartBtn.x + restartBtn.width &&",
        "        my >= restartBtn.y && my <= restartBtn.y + restartBtn.height) {",
        "      restart();",
        "    }",
        "    return;",
        "  }",
        "",
        "  frame++;",
        "  if (frame % " + spawnRate + " === 0) spawn();",
        "",
        "  const keyJump = display.keys[38] || display.keys[32] || display.keys[87];",
        "  const tapJump = display.x !== false;",
        "  if ((keyJump || tapJump) && onGround) {",
        "    vy = -13;",
        "    onGround = false;",
        "  }",
        "",
        "  vy += 40 * dt;",
        "  player.y += vy;",
        "",
        "  if (player.y >= 500) {",
        "    player.y = 500;",
        "    vy = 0;",
        "    onGround = true;",
        "  }",
        "",
        "  for (let i = obstacles.length - 1; i >= 0; i--) {",
        "    const o = obstacles[i];",
        "    o.x -= " + speed + ";",
        "    if (o.x < -60) {",
        "      o.destroy();",
        "      obstacles.splice(i, 1);",
        "      points += 5;",
        "      score.setText('Score: ' + points);",
        "    } else if (rectHit(player, o)) {",
        "      gameOver = true;",
        "      score.setText('Game Over! Score: ' + points);",
        "      showRestart();",
        "    }",
        "  }",
        "}"
      ].join("\n");
    }
  },

  shooter: {
    name: "Shooter",
    fields: [
      { key: "title",    label: "Title",             type: "text",  default: "Star Fight" },
      { key: "bg",       label: "Space",             type: "color", default: "#050510" },
      { key: "player",   label: "Ship",              type: "color", default: "#4af" },
      { key: "bullet",   label: "Bullet",            type: "color", default: "#fd3" },
      { key: "enemy",    label: "Enemy",             type: "color", default: "#f44" },
      { key: "speed",    label: "Move speed",        type: "text",  default: "320" },
      { key: "fireRate", label: "Fire rate (frames)",type: "text",  default: "12" },
      { key: "spawn",    label: "Enemy spawn",       type: "text",  default: "90" }
    ],
    config: function(cfg) {
      return {
        title: cfg.title,
        world: { w: 800, h: 600, bg: cfg.bg },
        slots: [
          { x: 380, y: 520, w: 40, h: 40, color: cfg.player },
          { x: 380, y: 300, w: 30, h: 30, color: cfg.enemy }
        ],
        palette: [cfg.player, cfg.bullet, cfg.enemy]
      };
    },
    generate: function(cfg) {
      var speed = parseInt(cfg.speed) || 320;
      var fireRate = parseInt(cfg.fireRate) || 12;
      var spawnRate = parseInt(cfg.spawn) || 90;
      return [
        "const display = new Display();",
        "display.perform();",
        "display.start(800, 600);",
        "display.backgroundColor('" + cfg.bg + "');",
        "",
        "const player = new Component(40, 40, '" + cfg.player + "', 380, 520, 'rect');",
        "display.add(player);",
        "",
        "const score = new Tctxt('20px','Arial','white',20,40,'left',false,'top','rgba(0,0,0,0.5)',10,4);",
        "score.setText('Score: 0');",
        "display.add(score);",
        "",
        "const BTN = 80;",
        "const BTN_Y = 500;",
        "function mkBtn(x, color) {",
        "  return new Component(BTN, BTN, color, x, BTN_Y, 'rect');",
        "}",
        "const btnL = mkBtn(20,  '#1a1a2e');",
        "const btnR = mkBtn(120, '#1a1a2e');",
        "const btnF = mkBtn(680, '#dc2626');",
        "const lblL = new Tctxt('36px','Arial','white',60,540,'center',false,'middle');",
        "const lblR = new Tctxt('36px','Arial','white',160,540,'center',false,'middle');",
        "const lblF = new Tctxt('16px','Arial','white',720,540,'center',false,'middle');",
        "lblL.setText('◀'); lblR.setText('▶'); lblF.setText('FIRE');",
        "display.add(btnL); display.add(btnR); display.add(btnF);",
        "display.add(lblL); display.add(lblR); display.add(lblF);",
        "",
        "function inBtn(b, x, y) {",
        "  return x >= b.x && x <= b.x + b.width && y >= b.y && y <= b.y + b.height;",
        "}",
        "",
        "let restartBtn = null;",
        "let restartLbl = null;",
        "",
        "const bullets = [];",
        "const enemies = [];",
        "let frame = 0;",
        "let points = 0;",
        "let gameOver = false;",
        "",
        "function rectHit(a, b) {",
        "  return a.x < b.x + b.width && a.x + a.width > b.x && a.y < b.y + b.height && a.y + a.height > b.y;",
        "}",
        "",
        "function showRestart() {",
        "  restartBtn = new Component(200, 60, '#2563eb', 300, 300, 'rect');",
        "  restartLbl = new Tctxt('24px','Arial','white',400,330,'center',false,'middle');",
        "  restartLbl.setText('▶ PLAY AGAIN');",
        "  display.add(restartBtn); display.add(restartLbl);",
        "}",
        "",
        "function restart() {",
        "  if (restartBtn) { restartBtn.destroy(); restartBtn = null; }",
        "  if (restartLbl) { restartLbl.destroy(); restartLbl = null; }",
        "  for (let i = bullets.length - 1; i >= 0; i--) bullets[i].destroy();",
        "  for (let i = enemies.length - 1; i >= 0; i--) enemies[i].destroy();",
        "  bullets.length = 0; enemies.length = 0;",
        "  player.x = 380; player.y = 520;",
        "  frame = 0; points = 0; gameOver = false;",
        "  score.setText('Score: 0');",
        "}",
        "",
        "function update(dt) {",
        "  if (gameOver) {",
        "    const mx = display.x, my = display.y;",
        "    if (mx !== false && restartBtn &&",
        "        mx >= restartBtn.x && mx <= restartBtn.x + restartBtn.width &&",
        "        my >= restartBtn.y && my <= restartBtn.y + restartBtn.height) {",
        "      restart();",
        "    }",
        "    return;",
        "  }",
        "",
        "  frame++;",
        "  const sp = " + speed + ";",
        "",
        "  const mx = display.x, my = display.y;",
        "  const touchingL = mx !== false && inBtn(btnL, mx, my);",
        "  const touchingR = mx !== false && inBtn(btnR, mx, my);",
        "  const touchingF = mx !== false && inBtn(btnF, mx, my);",
        "",
        "  if (display.keys[37] || display.keys[65] || touchingL) player.x -= sp * dt;",
        "  if (display.keys[39] || display.keys[68] || touchingR) player.x += sp * dt;",
        "",
        "  if (player.x < 0) player.x = 0;",
        "  if (player.x + player.width > 800) player.x = 800 - player.width;",
        "",
        "  const keyFire = display.keys[32] || display.keys[38];",
        "  if ((keyFire || touchingF) && frame % " + fireRate + " === 0) {",
        "    const b = new Component(6, 14, '" + cfg.bullet + "', player.x + 17, player.y - 10, 'rect');",
        "    display.add(b);",
        "    bullets.push(b);",
        "  }",
        "",
        "  for (let i = bullets.length - 1; i >= 0; i--) {",
        "    const b = bullets[i];",
        "    b.y -= 12;",
        "    if (b.y < -20) { b.destroy(); bullets.splice(i, 1); }",
        "  }",
        "",
        "  if (frame % " + spawnRate + " === 0) {",
        "    const e = new Component(36, 36, '" + cfg.enemy + "', 20 + Math.random() * 740, -40, 'rect');",
        "    display.add(e);",
        "    enemies.push(e);",
        "  }",
        "",
        "  for (let i = enemies.length - 1; i >= 0; i--) {",
        "    const e = enemies[i];",
        "    e.y += 2;",
        "",
        "    if (e.y > 620) { e.destroy(); enemies.splice(i, 1); continue; }",
        "",
        "    if (rectHit(player, e)) {",
        "      gameOver = true;",
        "      score.setText('Game Over! Score: ' + points);",
        "      showRestart();",
        "    }",
        "",
        "    for (let j = bullets.length - 1; j >= 0; j--) {",
        "      if (rectHit(bullets[j], e)) {",
        "        bullets[j].destroy(); bullets.splice(j, 1);",
        "        e.destroy(); enemies.splice(i, 1);",
        "        points += 10;",
        "        score.setText('Score: ' + points);",
        "        break;",
        "      }",
        "    }",
        "  }",
        "}"
      ].join("\n");
    }
  },

  clicker: {
    name: "Clicker",
    fields: [
      { key: "title",    label: "Title",              type: "text",  default: "Click Rush" },
      { key: "bg",       label: "Background",         type: "color", default: "#0d0d2a" },
      { key: "target",   label: "Target",             type: "color", default: "#4af" },
      { key: "size",     label: "Target size (px)",   type: "text",  default: "60" },
      { key: "lifetime", label: "Lifetime (frames)",  type: "text",  default: "90" },
      { key: "time",     label: "Game time (secs)",   type: "text",  default: "30" }
    ],
    config: function(cfg) {
      return {
        title: cfg.title,
        world: { w: 800, h: 600, bg: cfg.bg },
        slots: [
          { x: 370, y: 270, w: 60, h: 60, color: cfg.target }
        ],
        palette: [cfg.target]
      };
    },
    generate: function(cfg) {
      var size = parseInt(cfg.size) || 60;
      var life = parseInt(cfg.lifetime) || 90;
      var totalTime = parseInt(cfg.time) || 30;
      return [
        "const display = new Display();",
        "display.perform();",
        "display.start(800, 600);",
        "display.backgroundColor('" + cfg.bg + "');",
        "",
        "const score = new Tctxt('20px','Arial','white',20,40,'left',false,'top','rgba(0,0,0,0.5)',10,4);",
        "score.setText('Tap the square. Score: 0  Time: " + totalTime + "');",
        "display.add(score);",
        "",
        "let target = null;",
        "let points = 0;",
        "let timeLeft = " + totalTime + ";",
        "let timer = 0;",
        "let spawnTimer = 0;",
        "let gameOver = false;",
        "let mouseWasDown = false;",
        "",
        "let restartBtn = null;",
        "let restartLbl = null;",
        "",
        "function spawnTarget() {",
        "  if (target) target.destroy();",
        "  const s = " + size + ";",
        "  const x = Math.random() * (800 - s);",
        "  const y = 80 + Math.random() * (520 - s);",
        "  target = new Component(s, s, '" + cfg.target + "', x, y, 'rect');",
        "  display.add(target);",
        "}",
        "",
        "function showRestart() {",
        "  restartBtn = new Component(200, 60, '#2563eb', 300, 300, 'rect');",
        "  restartLbl = new Tctxt('24px','Arial','white',400,330,'center',false,'middle');",
        "  restartLbl.setText('▶ PLAY AGAIN');",
        "  display.add(restartBtn); display.add(restartLbl);",
        "}",
        "",
        "function restart() {",
        "  if (restartBtn) { restartBtn.destroy(); restartBtn = null; }",
        "  if (restartLbl) { restartLbl.destroy(); restartLbl = null; }",
        "  if (target) { target.destroy(); target = null; }",
        "  points = 0; timeLeft = " + totalTime + "; timer = 0; spawnTimer = 0;",
        "  gameOver = false;",
        "  score.setText('Tap the square. Score: 0  Time: " + totalTime + "');",
        "  spawnTarget();",
        "}",
        "",
        "spawnTarget();",
        "",
        "function update(dt) {",
        "  if (gameOver) {",
        "    const mx = display.x, my = display.y;",
        "    if (mx !== false && restartBtn &&",
        "        mx >= restartBtn.x && mx <= restartBtn.x + restartBtn.width &&",
        "        my >= restartBtn.y && my <= restartBtn.y + restartBtn.height) {",
        "      restart();",
        "    }",
        "    return;",
        "  }",
        "",
        "  timer += dt;",
        "  if (timer >= 1) {",
        "    timer -= 1;",
        "    timeLeft--;",
        "    score.setText('Score: ' + points + '  Time: ' + timeLeft);",
        "    if (timeLeft <= 0) {",
        "      gameOver = true;",
        "      if (target) target.destroy();",
        "      score.setText('Game Over! Final Score: ' + points);",
        "      showRestart();",
        "      return;",
        "    }",
        "  }",
        "",
        "  spawnTimer++;",
        "  if (!target || spawnTimer > " + life + ") {",
        "    spawnTarget();",
        "    spawnTimer = 0;",
        "  }",
        "",
        "  if (display.x !== false && !mouseWasDown && target) {",
        "    const mx = display.x, my = display.y;",
        "    if (mx >= target.x && mx <= target.x + target.width && my >= target.y && my <= target.y + target.height) {",
        "      points += 10;",
        "      score.setText('Score: ' + points + '  Time: ' + timeLeft);",
        "      target.destroy();",
        "      target = null;",
        "      spawnTarget();",
        "      spawnTimer = 0;",
        "    }",
        "    mouseWasDown = true;",
        "  }",
        "  if (display.x === false) mouseWasDown = false;",
        "}"
      ].join("\n");
    }
  },
breakout: {
  name: "Breakout",
  fields: [
    { key: "title",    label: "Title",           type: "text",  default: "Brick Buster" },
    { key: "bg",       label: "Background",      type: "color", default: "#0d0d2a" },
    { key: "paddle",   label: "Paddle",          type: "color", default: "#4af" },
    { key: "ball",     label: "Ball",            type: "color", default: "#ffffff" },
    { key: "brickA",   label: "Brick (top row)", type: "color", default: "#ec4899" },
    { key: "brickB",   label: "Brick (bottom)",  type: "color", default: "#22d3ee" },
    { key: "speed",    label: "Ball speed",      type: "text",  default: "5" }
  ],
  config: function(cfg) {
    return {
      title: cfg.title,
      world: { w: 800, h: 600, bg: cfg.bg },
      slots: [
        { x: 340, y: 540, w: 120, h: 20, color: cfg.paddle },
        { x: 400, y: 400, w: 16,  h: 16, color: cfg.ball },
        { x: 100, y: 60,  w: 76,  h: 20, color: cfg.brickA }
      ],
      palette: [cfg.paddle, cfg.ball, cfg.brickA, cfg.brickB]
    };
  },
  generate: function(cfg) {
    var speed = parseInt(cfg.speed) || 5;
    return [
      "const display = new Display();",
      "display.perform();",
      "display.start(800, 600);",
      "display.backgroundColor('" + cfg.bg + "');",
      "",
      "const paddle = new Component(120, 20, '" + cfg.paddle + "', 340, 540, 'rect');",
      "display.add(paddle);",
      "",
      "const ball = new Component(16, 16, '" + cfg.ball + "', 400, 400, 'rect');",
      "display.add(ball);",
      "let vx = " + speed + ", vy = -" + speed + ";",
      "",
      "const score = new Tctxt('20px','Arial','white',20,40,'left',false,'top','rgba(0,0,0,0.5)',10,4);",
      "score.setText('Score: 0');",
      "display.add(score);",
      "",
      "const bricks = [];",
      "const COLS = 8, ROWS = 5;",
      "const BW = 86, BH = 22, GAP = 6;",
      "const startX = (800 - COLS * BW - (COLS - 1) * GAP) / 2;",
      "for (let r = 0; r < ROWS; r++) {",
      "  const color = r < 2 ? '" + cfg.brickA + "' : '" + cfg.brickB + "';",
      "  for (let c = 0; c < COLS; c++) {",
      "    const b = new Component(BW, BH, color, startX + c * (BW + GAP), 70 + r * (BH + GAP), 'rect');",
      "    display.add(b);",
      "    bricks.push(b);",
      "  }",
      "}",
      "",
      "let points = 0;",
      "let gameOver = false;",
      "let won = false;",
      "let restartBtn = null;",
      "let restartLbl = null;",
      "",
      "function rectHit(a, b) {",
      "  return a.x < b.x + b.width && a.x + a.width > b.x && a.y < b.y + b.height && a.y + a.height > b.y;",
      "}",
      "",
      "function showRestart(msg) {",
      "  restartBtn = new Component(220, 60, '#2563eb', 290, 300, 'rect');",
      "  restartLbl = new Tctxt('22px','Arial','white',400,330,'center',false,'middle');",
      "  restartLbl.setText(msg);",
      "  display.add(restartBtn); display.add(restartLbl);",
      "}",
      "",
      "function restart() {",
      "  if (restartBtn) { restartBtn.destroy(); restartBtn = null; }",
      "  if (restartLbl) { restartLbl.destroy(); restartLbl = null; }",
      "  for (const b of bricks) b.destroy();",
      "  bricks.length = 0;",
      "  for (let r = 0; r < ROWS; r++) {",
      "    const color = r < 2 ? '" + cfg.brickA + "' : '" + cfg.brickB + "';",
      "    for (let c = 0; c < COLS; c++) {",
      "      const b = new Component(BW, BH, color, startX + c * (BW + GAP), 70 + r * (BH + GAP), 'rect');",
      "      display.add(b);",
      "      bricks.push(b);",
      "    }",
      "  }",
      "  ball.x = 400; ball.y = 400;",
      "  vx = " + speed + "; vy = -" + speed + ";",
      "  points = 0; gameOver = false; won = false;",
      "  score.setText('Score: 0');",
      "}",
      "",
      "const BTN = 100;",
      "const btnL = new Component(BTN, BTN, '#1a1a2e', 20, 480, 'rect');",
      "const btnR = new Component(BTN, BTN, '#1a1a2e', 680, 480, 'rect');",
      "display.add(btnL); display.add(btnR);",
      "",
      "function inBtn(b, x, y) {",
      "  return x >= b.x && x <= b.x + b.width && y >= b.y && y <= b.y + b.height;",
      "}",
      "",
      "function update(dt) {",
      "  if (gameOver || won) {",
      "    const mx = display.x, my = display.y;",
      "    if (mx !== false && restartBtn &&",
      "        mx >= restartBtn.x && mx <= restartBtn.x + restartBtn.width &&",
      "        my >= restartBtn.y && my <= restartBtn.y + restartBtn.height) restart();",
      "    return;",
      "  }",
      "",
      "  const mx = display.x, my = display.y;",
      "  const padSpeed = 480 * dt;",
      "  if (display.keys[37] || display.keys[65] || (mx !== false && inBtn(btnL, mx, my))) paddle.x -= padSpeed;",
      "  if (display.keys[39] || display.keys[68] || (mx !== false && inBtn(btnR, mx, my))) paddle.x += padSpeed;",
      "  if (paddle.x < 0) paddle.x = 0;",
      "  if (paddle.x + paddle.width > 800) paddle.x = 800 - paddle.width;",
      "",
      "  ball.x += vx;",
      "  ball.y += vy;",
      "",
      "  if (ball.x <= 0 || ball.x + ball.width >= 800) vx = -vx;",
      "  if (ball.y <= 0) vy = -vy;",
      "",
      "  if (vy > 0 && rectHit(ball, paddle)) {",
      "    vy = -vy;",
      "    const hit = (ball.x + ball.width / 2 - (paddle.x + paddle.width / 2)) / (paddle.width / 2);",
      "    vx = hit * " + speed + ";",
      "  }",
      "",
      "  if (ball.y > 600) {",
      "    gameOver = true;",
      "    score.setText('Game Over! Score: ' + points);",
      "    showRestart('▶ PLAY AGAIN');",
      "    return;",
      "  }",
      "",
      "  for (let i = bricks.length - 1; i >= 0; i--) {",
      "    if (rectHit(ball, bricks[i])) {",
      "      bricks[i].destroy();",
      "      bricks.splice(i, 1);",
      "      vy = -vy;",
      "      points += 10;",
      "      score.setText('Score: ' + points);",
      "      break;",
      "    }",
      "  }",
      "",
      "  if (bricks.length === 0) {",
      "    won = true;",
      "    score.setText('You win! Score: ' + points);",
      "    showRestart('▶ PLAY AGAIN');",
      "  }",
      "}"
    ].join("\n");
  }
},

flappy: {
  name: "Flappy",
  fields: [
    { key: "title",  label: "Title",         type: "text",  default: "Flappy Square" },
    { key: "bg",     label: "Sky",           type: "color", default: "#0d0d2a" },
    { key: "player", label: "Player",        type: "color", default: "#fd3" },
    { key: "pipe",   label: "Pipes",         type: "color", default: "#4f8" },
    { key: "gravity",label: "Gravity (1-4)", type: "text",  default: "2" },
    { key: "flap",   label: "Flap force",    type: "text",  default: "9" },
    { key: "speed",  label: "Scroll speed",  type: "text",  default: "3" }
  ],
  config: function(cfg) {
    return {
      title: cfg.title,
      world: { w: 800, h: 600, bg: cfg.bg },
      slots: [
        { x: 120, y: 280, w: 40, h: 40, color: cfg.player },
        { x: 700, y: 100, w: 70, h: 220, color: cfg.pipe }
      ],
      palette: [cfg.player, cfg.pipe]
    };
  },
  generate: function(cfg) {
    var gravity = parseFloat(cfg.gravity) || 2;
    var flap = parseFloat(cfg.flap) || 9;
    var speed = parseInt(cfg.speed) || 3;
    return [
      "const display = new Display();",
      "display.perform();",
      "display.start(800, 600);",
      "display.backgroundColor('" + cfg.bg + "');",
      "",
      "const player = new Component(40, 40, '" + cfg.player + "', 120, 280, 'rect');",
      "player.changeAngle = false;",
      "display.add(player);",
      "",
      "const score = new Tctxt('22px','Arial','white',400,60,'center',false,'top','rgba(0,0,0,0.5)',14,6);",
      "score.setText('Tap to flap. Score: 0');",
      "display.add(score);",
      "",
      "const pipes = [];",
      "let vy = 0;",
      "let points = 0;",
      "let frame = 0;",
      "let gameOver = false;",
      "let restartBtn = null;",
      "let restartLbl = null;",
      "",
      "const GAP = 180;",
      "const PIPE_W = 70;",
      "",
      "function rectHit(a, b) {",
      "  return a.x < b.x + b.width && a.x + a.width > b.x && a.y < b.y + b.height && a.y + a.height > b.y;",
      "}",
      "",
      "function spawnPipe() {",
      "  const topH = 80 + Math.random() * 240;",
      "  const bottomY = topH + GAP;",
      "  const bottomH = 600 - bottomY;",
      "  const top = new Component(PIPE_W, topH, '" + cfg.pipe + "', 820, 0, 'rect');",
      "  const bot = new Component(PIPE_W, bottomH, '" + cfg.pipe + "', 820, bottomY, 'rect');",
      "  top.scored = false;",
      "  top.isTop = true;",
      "  bot.isTop = false;",
      "  display.add(top); display.add(bot);",
      "  pipes.push(top); pipes.push(bot);",
      "}",
      "",
      "function showRestart() {",
      "  restartBtn = new Component(220, 60, '#2563eb', 290, 280, 'rect');",
      "  restartLbl = new Tctxt('22px','Arial','white',400,310,'center',false,'middle');",
      "  restartLbl.setText('▶ PLAY AGAIN');",
      "  display.add(restartBtn); display.add(restartLbl);",
      "}",
      "",
      "function restart() {",
      "  if (restartBtn) { restartBtn.destroy(); restartBtn = null; }",
      "  if (restartLbl) { restartLbl.destroy(); restartLbl = null; }",
      "  for (const p of pipes) p.destroy();",
      "  pipes.length = 0;",
      "  player.x = 120; player.y = 280;",
      "  vy = 0; points = 0; frame = 0; gameOver = false;",
      "  score.setText('Tap to flap. Score: 0');",
      "}",
      "",
      "function update(dt) {",
      "  if (gameOver) {",
      "    const mx = display.x, my = display.y;",
      "    if (mx !== false && restartBtn &&",
      "        mx >= restartBtn.x && mx <= restartBtn.x + restartBtn.width &&",
      "        my >= restartBtn.y && my <= restartBtn.y + restartBtn.height) restart();",
      "    return;",
      "  }",
      "",
      "  frame++;",
      "  if (frame % 90 === 0) spawnPipe();",
      "",
      "  const keyFlap = display.keys[32] || display.keys[38] || display.keys[87];",
      "  const tapFlap = display.x !== false;",
      "  if (keyFlap || tapFlap) vy = -" + flap + ";",
      "",
      "  vy += " + gravity + ";",
      "  player.y += vy;",
      "",
      "  if (player.y < 0) { player.y = 0; vy = 0; }",
      "  if (player.y + player.height > 600) {",
      "    gameOver = true;",
      "    score.setText('Game Over! Score: ' + points);",
      "    showRestart();",
      "    return;",
      "  }",
      "",
      "  for (let i = pipes.length - 1; i >= 0; i--) {",
      "    const p = pipes[i];",
      "    p.x -= " + speed + ";",
      "",
      "    if (p.x + p.width < 0) {",
      "      p.destroy();",
      "      pipes.splice(i, 1);",
      "      continue;",
      "    }",
      "",
      "    if (rectHit(player, p)) {",
      "      gameOver = true;",
      "      score.setText('Game Over! Score: ' + points);",
      "      showRestart();",
      "      return;",
      "    }",
      "",
      "    if (p.isTop && !p.scored && p.x + p.width < player.x) {",
      "      p.scored = true;",
      "      points++;",
      "      score.setText('Score: ' + points);",
      "    }",
      "  }",
      "}"
    ].join("\n");
  }
},

snake: {
  name: "Snake",
  fields: [
    { key: "title",    label: "Title",        type: "text",  default: "Snake" },
    { key: "bg",       label: "Background",   type: "color", default: "#0d0d2a" },
    { key: "snake",    label: "Snake body",   type: "color", default: "#4f8" },
    { key: "head",     label: "Snake head",   type: "color", default: "#7fffb2" },
    { key: "food",     label: "Food",         type: "color", default: "#f44" },
    { key: "cell",     label: "Cell size (px)",type: "text",  default: "30" },
    { key: "tickRate", label: "Speed (frames)",type: "text",  default: "8" }
  ],
  config: function(cfg) {
    return {
      title: cfg.title,
      world: { w: 800, h: 600, bg: cfg.bg },
      slots: [
        { x: 400, y: 300, w: 30, h: 30, color: cfg.head },
        { x: 340, y: 300, w: 30, h: 30, color: cfg.snake },
        { x: 600, y: 300, w: 30, h: 30, color: cfg.food }
      ],
      palette: [cfg.snake, cfg.head, cfg.food]
    };
  },
  generate: function(cfg) {
    var cell = parseInt(cfg.cell) || 30;
    var tick = parseInt(cfg.tickRate) || 8;
    return [
      "const display = new Display();",
      "display.perform();",
      "display.start(800, 600);",
      "display.backgroundColor('" + cfg.bg + "');",
      "",
      "const CELL = " + cell + ";",
      "const COLS = Math.floor(800 / CELL);",
      "const ROWS = Math.floor(600 / CELL);",
      "",
      "const score = new Tctxt('20px','Arial','white',20,40,'left',false,'top','rgba(0,0,0,0.5)',10,4);",
      "score.setText('Score: 0');",
      "display.add(score);",
      "",
      "let snake = [{ x: 10, y: 10 }, { x: 9, y: 10 }, { x: 8, y: 10 }];",
      "let dir = { x: 1, y: 0 };",
      "let nextDir = { x: 1, y: 0 };",
      "let food = { x: 20, y: 10 };",
      "let cells = [];",
      "let foodComp = null;",
      "let frame = 0;",
      "let points = 0;",
      "let gameOver = false;",
      "let restartBtn = null;",
      "let restartLbl = null;",
      "",
      "function makeCell(color) {",
      "  const c = new Component(CELL - 2, CELL - 2, color, 0, 0, 'rect');",
      "  c.changeAngle = false;",
      "  display.add(c);",
      "  return c;",
      "}",
      "",
      "function draw() {",
      "  while (cells.length < snake.length) cells.push(makeCell('" + cfg.snake + "'));",
      "  for (let i = 0; i < snake.length; i++) {",
      "    const s = snake[i];",
      "    const c = cells[i];",
      "    c.x = s.x * CELL + 1;",
      "    c.y = s.y * CELL + 1;",
      "    c.color = i === 0 ? '" + cfg.head + "' : '" + cfg.snake + "';",
      "  }",
      "  for (let i = snake.length; i < cells.length; i++) cells[i].x = -100;",
      "}",
      "",
      "function placeFood() {",
      "  while (true) {",
      "    food.x = Math.floor(Math.random() * COLS);",
      "    food.y = Math.floor(Math.random() * ROWS);",
      "    if (!snake.some(s => s.x === food.x && s.y === food.y)) break;",
      "  }",
      "  if (foodComp) foodComp.destroy();",
      "  foodComp = makeCell('" + cfg.food + "');",
      "  foodComp.x = food.x * CELL + 1;",
      "  foodComp.y = food.y * CELL + 1;",
      "}",
      "",
      "function showRestart() {",
      "  restartBtn = new Component(220, 60, '#2563eb', 290, 280, 'rect');",
      "  restartLbl = new Tctxt('22px','Arial','white',400,310,'center',false,'middle');",
      "  restartLbl.setText('▶ PLAY AGAIN');",
      "  display.add(restartBtn); display.add(restartLbl);",
      "}",
      "",
      "function restart() {",
      "  if (restartBtn) { restartBtn.destroy(); restartBtn = null; }",
      "  if (restartLbl) { restartLbl.destroy(); restartLbl = null; }",
      "  for (const c of cells) c.destroy();",
      "  cells.length = 0;",
      "  if (foodComp) { foodComp.destroy(); foodComp = null; }",
      "  snake = [{ x: 10, y: 10 }, { x: 9, y: 10 }, { x: 8, y: 10 }];",
      "  dir = { x: 1, y: 0 }; nextDir = { x: 1, y: 0 };",
      "  points = 0; frame = 0; gameOver = false;",
      "  score.setText('Score: 0');",
      "  placeFood();",
      "  draw();",
      "}",
      "",
      "function setDir(x, y) {",
      "  if (dir.x === -x && dir.y === -y) return;",
      "  nextDir = { x: x, y: y };",
      "}",
      "",
      "const btnSize = 80;",
      "const btnUp = new Component(btnSize, btnSize, '#1a1a2e', 360, 460, 'rect');",
      "const btnDown = new Component(btnSize, btnSize, '#1a1a2e', 360, 560, 'rect');",
      "const btnLeft = new Component(btnSize, btnSize, '#1a1a2e', 260, 510, 'rect');",
      "const btnRight = new Component(btnSize, btnSize, '#1a1a2e', 460, 510, 'rect');",
      "display.add(btnUp); display.add(btnDown); display.add(btnLeft); display.add(btnRight);",
      "",
      "function inBtn(b, x, y) {",
      "  return x >= b.x && x <= b.x + b.width && y >= b.y && y <= b.y + b.height;",
      "}",
      "",
      "placeFood();",
      "draw();",
      "",
      "function update(dt) {",
      "  if (gameOver) {",
      "    const mx = display.x, my = display.y;",
      "    if (mx !== false && restartBtn &&",
      "        mx >= restartBtn.x && mx <= restartBtn.x + restartBtn.width &&",
      "        my >= restartBtn.y && my <= restartBtn.y + restartBtn.height) restart();",
      "    return;",
      "  }",
      "",
      "  const mx = display.x, my = display.y;",
      "  if (display.keys[38] || display.keys[87] || (mx !== false && inBtn(btnUp, mx, my))) setDir(0, -1);",
      "  if (display.keys[40] || display.keys[83] || (mx !== false && inBtn(btnDown, mx, my))) setDir(0, 1);",
      "  if (display.keys[37] || display.keys[65] || (mx !== false && inBtn(btnLeft, mx, my))) setDir(-1, 0);",
      "  if (display.keys[39] || display.keys[68] || (mx !== false && inBtn(btnRight, mx, my))) setDir(1, 0);",
      "",
      "  frame++;",
      "  if (frame < " + tick + ") return;",
      "  frame = 0;",
      "",
      "  dir = nextDir;",
      "  const head = { x: snake[0].x + dir.x, y: snake[0].y + dir.y };",
      "",
      "  if (head.x < 0 || head.x >= COLS || head.y < 0 || head.y >= ROWS ||",
      "      snake.some(s => s.x === head.x && s.y === head.y)) {",
      "    gameOver = true;",
      "    score.setText('Game Over! Score: ' + points);",
      "    showRestart();",
      "    return;",
      "  }",
      "",
      "  snake.unshift(head);",
      "  if (head.x === food.x && head.y === food.y) {",
      "    points += 10;",
      "    score.setText('Score: ' + points);",
      "    placeFood();",
      "  } else {",
      "    snake.pop();",
      "  }",
      "  draw();",
      "}"
    ].join("\n");
  }
},

catch: {
  name: "Catch",
  fields: [
    { key: "title",  label: "Title",         type: "text",  default: "Catch It" },
    { key: "bg",     label: "Background",    type: "color", default: "#0d0d2a" },
    { key: "basket", label: "Basket",        type: "color", default: "#4af" },
    { key: "fruit",  label: "Fruit",         type: "color", default: "#4f8" },
    { key: "bomb",   label: "Bomb",          type: "color", default: "#f44" },
    { key: "speed",  label: "Basket speed",  type: "text",  default: "420" },
    { key: "fall",   label: "Fall speed",    type: "text",  default: "4" },
    { key: "rate",   label: "Spawn (frames)",type: "text",  default: "45" }
  ],
  config: function(cfg) {
    return {
      title: cfg.title,
      world: { w: 800, h: 600, bg: cfg.bg },
      slots: [
        { x: 350, y: 540, w: 100, h: 30, color: cfg.basket },
        { x: 300, y: 200, w: 28, h: 28, color: cfg.fruit },
        { x: 500, y: 200, w: 28, h: 28, color: cfg.bomb }
      ],
      palette: [cfg.basket, cfg.fruit, cfg.bomb]
    };
  },
  generate: function(cfg) {
    var speed = parseInt(cfg.speed) || 420;
    var fall = parseInt(cfg.fall) || 4;
    var rate = parseInt(cfg.rate) || 45;
    return [
      "const display = new Display();",
      "display.perform();",
      "display.start(800, 600);",
      "display.backgroundColor('" + cfg.bg + "');",
      "",
      "const basket = new Component(100, 30, '" + cfg.basket + "', 350, 540, 'rect');",
      "display.add(basket);",
      "",
      "const score = new Tctxt('20px','Arial','white',20,40,'left',false,'top','rgba(0,0,0,0.5)',10,4);",
      "score.setText('Score: 0  Lives: 3');",
      "display.add(score);",
      "",
      "const items = [];",
      "let frame = 0;",
      "let points = 0;",
      "let lives = 3;",
      "let gameOver = false;",
      "let restartBtn = null;",
      "let restartLbl = null;",
      "",
      "function rectHit(a, b) {",
      "  return a.x < b.x + b.width && a.x + a.width > b.x && a.y < b.y + b.height && a.y + a.height > b.y;",
      "}",
      "",
      "function spawn() {",
      "  const isBomb = Math.random() < 0.25;",
      "  const x = 20 + Math.random() * 740;",
      "  const color = isBomb ? '" + cfg.bomb + "' : '" + cfg.fruit + "';",
      "  const it = new Component(28, 28, color, x, -30, 'rect');",
      "  it.isBomb = isBomb;",
      "  display.add(it);",
      "  items.push(it);",
      "}",
      "",
      "function showRestart() {",
      "  restartBtn = new Component(220, 60, '#2563eb', 290, 280, 'rect');",
      "  restartLbl = new Tctxt('22px','Arial','white',400,310,'center',false,'middle');",
      "  restartLbl.setText('▶ PLAY AGAIN');",
      "  display.add(restartBtn); display.add(restartLbl);",
      "}",
      "",
      "function restart() {",
      "  if (restartBtn) { restartBtn.destroy(); restartBtn = null; }",
      "  if (restartLbl) { restartLbl.destroy(); restartLbl = null; }",
      "  for (const it of items) it.destroy();",
      "  items.length = 0;",
      "  basket.x = 350;",
      "  points = 0; lives = 3; frame = 0; gameOver = false;",
      "  score.setText('Score: 0  Lives: 3');",
      "}",
      "",
      "const btnL = new Component(100, 100, '#1a1a2e', 20, 480, 'rect');",
      "const btnR = new Component(100, 100, '#1a1a2e', 680, 480, 'rect');",
      "display.add(btnL); display.add(btnR);",
      "",
      "function inBtn(b, x, y) {",
      "  return x >= b.x && x <= b.x + b.width && y >= b.y && y <= b.y + b.height;",
      "}",
      "",
      "function update(dt) {",
      "  if (gameOver) {",
      "    const mx = display.x, my = display.y;",
      "    if (mx !== false && restartBtn &&",
      "        mx >= restartBtn.x && mx <= restartBtn.x + restartBtn.width &&",
      "        my >= restartBtn.y && my <= restartBtn.y + restartBtn.height) restart();",
      "    return;",
      "  }",
      "",
      "  frame++;",
      "  if (frame % " + rate + " === 0) spawn();",
      "",
      "  const mx = display.x, my = display.y;",
      "  const sp = " + speed + " * dt;",
      "  if (display.keys[37] || display.keys[65] || (mx !== false && inBtn(btnL, mx, my))) basket.x -= sp;",
      "  if (display.keys[39] || display.keys[68] || (mx !== false && inBtn(btnR, mx, my))) basket.x += sp;",
      "  if (basket.x < 0) basket.x = 0;",
      "  if (basket.x + basket.width > 800) basket.x = 800 - basket.width;",
      "",
      "  for (let i = items.length - 1; i >= 0; i--) {",
      "    const it = items[i];",
      "    it.y += " + fall + ";",
      "",
      "    if (it.y > 620) {",
      "      it.destroy();",
      "      items.splice(i, 1);",
      "      if (!it.isBomb) {",
      "        lives--;",
      "        score.setText('Score: ' + points + '  Lives: ' + lives);",
      "        if (lives <= 0) {",
      "          gameOver = true;",
      "          score.setText('Game Over! Score: ' + points);",
      "          showRestart();",
      "          return;",
      "        }",
      "      }",
      "      continue;",
      "    }",
      "",
      "    if (rectHit(it, basket)) {",
      "      it.destroy();",
      "      items.splice(i, 1);",
      "      if (it.isBomb) {",
      "        lives--;",
      "        score.setText('Score: ' + points + '  Lives: ' + lives);",
      "        if (lives <= 0) {",
      "          gameOver = true;",
      "          score.setText('Game Over! Score: ' + points);",
      "          showRestart();",
      "          return;",
      "        }",
      "      } else {",
      "        points += 10;",
      "        score.setText('Score: ' + points + '  Lives: ' + lives);",
      "      }",
      "    }",
      "  }",
      "}"
    ].join("\n");
  }
},

dodge: {
  name: "Dodge",
  fields: [
    { key: "title",   label: "Title",          type: "text",  default: "Dodge!" },
    { key: "bg",      label: "Background",     type: "color", default: "#0d0d2a" },
    { key: "player",  label: "Player",         type: "color", default: "#4af" },
    { key: "wall",    label: "Wall",           type: "color", default: "#f44" },
    { key: "speed",   label: "Move speed",     type: "text",  default: "380" },
    { key: "rate",    label: "Spawn (frames)", type: "text",  default: "35" }
  ],
  config: function(cfg) {
    return {
      title: cfg.title,
      world: { w: 800, h: 600, bg: cfg.bg },
      slots: [
        { x: 380, y: 280, w: 40, h: 40, color: cfg.player },
        { x: 0, y: 0, w: 120, h: 120, color: cfg.wall }
      ],
      palette: [cfg.player, cfg.wall]
    };
  },
  generate: function(cfg) {
    var speed = parseInt(cfg.speed) || 380;
    var rate = parseInt(cfg.rate) || 35;
    return [
      "const display = new Display();",
      "display.perform();",
      "display.start(800, 600);",
      "display.backgroundColor('" + cfg.bg + "');",
      "",
      "const player = new Component(40, 40, '" + cfg.player + "', 380, 280, 'rect');",
      "player.changeAngle = false;",
      "display.add(player);",
      "",
      "const score = new Tctxt('20px','Arial','white',20,40,'left',false,'top','rgba(0,0,0,0.5)',10,4);",
      "score.setText('Survive! Time: 0');",
      "display.add(score);",
      "",
      "const blocks = [];",
      "let frame = 0;",
      "let timeAlive = 0;",
      "let timer = 0;",
      "let gameOver = false;",
      "let restartBtn = null;",
      "let restartLbl = null;",
      "",
      "function rectHit(a, b) {",
      "  return a.x < b.x + b.width && a.x + a.width > b.x && a.y < b.y + b.height && a.y + a.height > b.y;",
      "}",
      "",
      "function spawnWave() {",
      "  const fromTop = Math.random() < 0.5;",
      "  const size = 60 + Math.random() * 60;",
      "  let b;",
      "  if (fromTop) {",
      "    b = new Component(size, size, '" + cfg.wall + "', Math.random() * (800 - size), -size, 'rect');",
      "    b.vy = 2 + Math.random() * 3;",
      "    b.vx = 0;",
      "  } else {",
      "    b = new Component(size, size, '" + cfg.wall + "', Math.random() < 0.5 ? -size : 800, Math.random() * 500, 'rect');",
      "    b.vx = (b.x < 0 ? 1 : -1) * (2 + Math.random() * 3);",
      "    b.vy = 0;",
      "  }",
      "  b.changeAngle = false;",
      "  display.add(b);",
      "  blocks.push(b);",
      "}",
      "",
      "function showRestart() {",
      "  restartBtn = new Component(220, 60, '#2563eb', 290, 280, 'rect');",
      "  restartLbl = new Tctxt('22px','Arial','white',400,310,'center',false,'middle');",
      "  restartLbl.setText('▶ PLAY AGAIN');",
      "  display.add(restartBtn); display.add(restartLbl);",
      "}",
      "",
      "function restart() {",
      "  if (restartBtn) { restartBtn.destroy(); restartBtn = null; }",
      "  if (restartLbl) { restartLbl.destroy(); restartLbl = null; }",
      "  for (const b of blocks) b.destroy();",
      "  blocks.length = 0;",
      "  player.x = 380; player.y = 280;",
      "  timeAlive = 0; timer = 0; frame = 0; gameOver = false;",
      "  score.setText('Survive! Time: 0');",
      "}",
      "",
      "function update(dt) {",
      "  if (gameOver) {",
      "    const mx = display.x, my = display.y;",
      "    if (mx !== false && restartBtn &&",
      "        mx >= restartBtn.x && mx <= restartBtn.x + restartBtn.width &&",
      "        my >= restartBtn.y && my <= restartBtn.y + restartBtn.height) restart();",
      "    return;",
      "  }",
      "",
      "  frame++;",
      "  timer += dt;",
      "  if (timer >= 1) { timer -= 1; timeAlive++; score.setText('Survive! Time: ' + timeAlive); }",
      "",
      "  const spawnEvery = Math.max(12, " + rate + " - Math.floor(timeAlive / 3));",
      "  if (frame % spawnEvery === 0) spawnWave();",
      "",
      "  const sp = " + speed + " * dt;",
      "  if (display.keys[37] || display.keys[65]) player.x -= sp;",
      "  if (display.keys[39] || display.keys[68]) player.x += sp;",
      "  if (display.keys[38] || display.keys[87]) player.y -= sp;",
      "  if (display.keys[40] || display.keys[83]) player.y += sp;",
      "  if (player.x < 0) player.x = 0;",
      "  if (player.x + player.width > 800) player.x = 800 - player.width;",
      "  if (player.y < 80) player.y = 80;",
      "  if (player.y + player.height > 600) player.y = 600 - player.height;",
      "",
      "  const sp2 = 320 * dt;",
      "  const mx = display.x, my = display.y;",
      "  if (mx !== false && my !== false) {",
      "    player.x += (mx - 20 - player.x) * 8 * dt;",
      "    player.y += (my - 20 - player.y) * 8 * dt;",
      "  }",
      "",
      "  for (let i = blocks.length - 1; i >= 0; i--) {",
      "    const b = blocks[i];",
      "    b.x += b.vx || 0;",
      "    b.y += b.vy || 0;",
      "",
      "    if (b.x > 900 || b.x < -200 || b.y > 700 || b.y < -200) {",
      "      b.destroy();",
      "      blocks.splice(i, 1);",
      "      continue;",
      "    }",
      "",
      "    if (rectHit(player, b)) {",
      "      gameOver = true;",
      "      score.setText('Game Over! Survived: ' + timeAlive + 's');",
      "      showRestart();",
      "      return;",
      "    }",
      "  }",
      "}"
    ].join("\n");
  }
},
};
