window.LimnTemplates = {

  dressup: {
    name: "Dress-Up",
    fields: [
      { key: "title",      label: "Title",      type: "text",  default: "My Outfit" },
      { key: "bg",         label: "Background", type: "color", default: "#0d0d2a" },
      { key: "hatColor",   label: "Hat",        type: "color", default: "#4af" },
      { key: "headColor",  label: "Head",       type: "color", default: "#fd3" },
      { key: "shirtColor", label: "Shirt",      type: "color", default: "#f44" },
      { key: "pantsColor", label: "Pants",      type: "color", default: "#c4f" },
      { key: "shoesColor", label: "Shoes",      type: "color", default: "#111" }
    ],
    config: function(cfg) {
      return {
        title: cfg.title,
        world: { w: 800, h: 600, bg: cfg.bg },
        slots: [
          { x: 355, y: 140, w: 90,  h: 30,  color: cfg.hatColor },
          { x: 360, y: 170, w: 80,  h: 80,  color: cfg.headColor },
          { x: 350, y: 250, w: 100, h: 120, color: cfg.shirtColor },
          { x: 355, y: 370, w: 90,  h: 90,  color: cfg.pantsColor },
          { x: 350, y: 460, w: 100, h: 30,  color: cfg.shoesColor }
        ],
        palette: [cfg.hatColor, cfg.headColor, cfg.shirtColor,
                  cfg.pantsColor, cfg.shoesColor, "#ffffff", "#111111"]
      };
    },
    generate: function(cfg) {
      var slots = [
        { x: 355, y: 140, w: 90,  h: 30,  color: cfg.hatColor },
        { x: 360, y: 170, w: 80,  h: 80,  color: cfg.headColor },
        { x: 350, y: 250, w: 100, h: 120, color: cfg.shirtColor },
        { x: 355, y: 370, w: 90,  h: 90,  color: cfg.pantsColor },
        { x: 350, y: 460, w: 100, h: 30,  color: cfg.shoesColor }
      ];
      var palette = [cfg.hatColor, cfg.headColor, cfg.shirtColor,
                     cfg.pantsColor, cfg.shoesColor, "#ffffff", "#111111"];
      return [
        "const display = new Display();",
        "display.perform();",
        "display.start(800, 600);",
        "display.backgroundColor('" + cfg.bg + "');",
        "",
        "const slots = " + JSON.stringify(slots) + ";",
        "const palette = " + JSON.stringify(palette) + ";",
        "",
        "const parts = slots.map((s, i) => {",
        "  const c = new Component(s.w, s.h, s.color, s.x, s.y, 'rect');",
        "  display.add(c);",
        "  c.slotIndex = i;",
        "  return c;",
        "});",
        "",
        "let mouseWasDown = false;",
        "",
        "function update(dt) {",
        "  if (display.x !== false && !mouseWasDown) {",
        "    const mx = display.x, my = display.y;",
        "    for (const p of parts) {",
        "      if (mx >= p.x && mx <= p.x + p.width && my >= p.y && my <= p.y + p.height) {",
        "        const cur = palette.indexOf(p.color);",
        "        p.color = palette[(cur + 1) % palette.length];",
        "        break;",
        "      }",
        "    }",
        "    mouseWasDown = true;",
        "  }",
        "  if (display.x === false) mouseWasDown = false;",
        "}"
      ].join("\n");
    }
  },

  platformer: {
    name: "Platformer",
    fields: [
      { key: "title",     label: "Title",           type: "text",  default: "Jump Quest" },
      { key: "bg",        label: "Sky",             type: "color", default: "#0d0d2a" },
      { key: "ground",    label: "Ground",          type: "color", default: "#4f8" },
      { key: "player",    label: "Player",          type: "color", default: "#4af" },
      { key: "coin",      label: "Coin",            type: "color", default: "#fd3" },
      { key: "speed",     label: "Speed (100-500)", type: "text",  default: "280" },
      { key: "jumpForce", label: "Jump (8-20)",     type: "text",  default: "13" },
      { key: "coins",     label: "Number of coins", type: "text",  default: "5" }
    ],
    config: function(cfg) {
      return {
        title: cfg.title,
        world: { w: 800, h: 600, bg: cfg.bg },
        slots: [
          { x: 100, y: 500, w: 40, h: 40, color: cfg.player },
          { x: 240, y: 380, w: 24, h: 24, color: cfg.coin }
        ],
        palette: [cfg.player, cfg.coin, cfg.ground]
      };
    },
    generate: function(cfg) {
      var speed = parseInt(cfg.speed) || 280;
      var jump = parseInt(cfg.jumpForce) || 13;
      var count = parseInt(cfg.coins) || 5;

      var coinPositions = [];
      var seed = 42;
      for (var i = 0; i < count; i++) {
        seed = (seed * 9301 + 49297) % 233280;
        var rnd = seed / 233280;
        var x = 120 + Math.floor(rnd * 580);
        var y = 380 - (i % 3) * 80;
        coinPositions.push({ x: x, y: y });
      }

      return [
        "const display = new Display();",
        "display.perform();",
        "display.start(800, 600);",
        "display.backgroundColor('" + cfg.bg + "');",
        "",
        "const player = new Component(40, 40, '" + cfg.player + "', 100, 400, 'rect');",
        "display.add(player);",
        "",
        "const ground = new Component(800, 60, '" + cfg.ground + "', 0, 540, 'rect');",
        "display.add(ground);",
        "",
        "const platforms = [",
        "  new Component(150, 20, '" + cfg.ground + "', 200, 460, 'rect'),",
        "  new Component(150, 20, '" + cfg.ground + "', 450, 380, 'rect'),",
        "  new Component(150, 20, '" + cfg.ground + "', 650, 300, 'rect')",
        "];",
        "platforms.forEach(function(p) { display.add(p); });",
        "",
        "const coinPositions = " + JSON.stringify(coinPositions) + ";",
        "const coins = coinPositions.map(function(c) {",
        "  var coin = new Component(24, 24, '" + cfg.coin + "', c.x, c.y, 'rect');",
        "  display.add(coin);",
        "  return coin;",
        "});",
        "",
        "const score = new Tctxt('20px','Arial','white',20,40,'left',false,'top','rgba(0,0,0,0.5)',10,4);",
        "score.setText('Score: 0');",
        "display.add(score);",
        "",
        "const BTN = 80;",
        "const BTN_Y = 500;",
        "function mkBtn(x, color) {",
        "  return new Component(BTN, BTN, color, x, BTN_Y, 'rect');",
        "}",
        "const btnL = mkBtn(20,  '#1a1a2e');",
        "const btnR = mkBtn(120, '#1a1a2e');",
        "const btnJ = mkBtn(680, '#2563eb');",
        "const lblL = new Tctxt('36px','Arial','white',60,540,'center',false,'middle');",
        "const lblR = new Tctxt('36px','Arial','white',160,540,'center',false,'middle');",
        "const lblJ = new Tctxt('16px','Arial','white',720,540,'center',false,'middle');",
        "lblL.setText('◀'); lblR.setText('▶'); lblJ.setText('JUMP');",
        "display.add(btnL); display.add(btnR); display.add(btnJ);",
        "display.add(lblL); display.add(lblR); display.add(lblJ);",
        "",
        "function inBtn(b, x, y) {",
        "  return x >= b.x && x <= b.x + b.width && y >= b.y && y <= b.y + b.height;",
        "}",
        "",
        "let vy = 0;",
        "let onGround = false;",
        "let points = 0;",
        "let won = false;",
        "",
        "function rectHit(a, b) {",
        "  return a.x < b.x + b.width && a.x + a.width > b.x && a.y < b.y + b.height && a.y + a.height > b.y;",
        "}",
        "",
        "function update(dt) {",
        "  if (won) return;",
        "  const sp = " + speed + ";",
        "  const jf = " + jump + ";",
        "",
        "  const mx = display.x, my = display.y;",
        "  const touchingL = mx !== false && inBtn(btnL, mx, my);",
        "  const touchingR = mx !== false && inBtn(btnR, mx, my);",
        "  const touchingJ = mx !== false && inBtn(btnJ, mx, my);",
        "",
        "  if (display.keys[37] || display.keys[65] || touchingL) player.x -= sp * dt;",
        "  if (display.keys[39] || display.keys[68] || touchingR) player.x += sp * dt;",
        "",
        "  const keyJump = display.keys[38] || display.keys[32] || display.keys[87];",
        "  if ((keyJump || touchingJ) && onGround) {",
        "    vy = -jf;",
        "    onGround = false;",
        "  }",
        "",
        "  vy += 40 * dt;",
        "  player.y += vy;",
        "  onGround = false;",
        "",
        "  if (rectHit(player, ground)) {",
        "    player.y = ground.y - player.height;",
        "    vy = 0;",
        "    onGround = true;",
        "  }",
        "",
        "  for (const p of platforms) {",
        "    if (rectHit(player, p) && player.y + player.height - vy <= p.y + 4) {",
        "      player.y = p.y - player.height;",
        "      vy = 0;",
        "      onGround = true;",
        "    }",
        "  }",
        "",
        "  if (player.x < 0) player.x = 0;",
        "  if (player.x + player.width > 800) player.x = 800 - player.width;",
        "",
        "  for (let i = coins.length - 1; i >= 0; i--) {",
        "    if (rectHit(player, coins[i])) {",
        "      coins[i].destroy();",
        "      coins.splice(i, 1);",
        "      points += 10;",
        "      score.setText('Score: ' + points);",
        "    }",
        "  }",
        "",
        "  if (coins.length === 0 && !won) {",
        "    won = true;",
        "    score.setText('You win! Score: ' + points);",
        "  }",
        "}"
      ].join("\n");
    }
  },

  runner: {
    name: "Runner",
    fields: [
      { key: "title",    label: "Title",               type: "text",  default: "Speed Run" },
      { key: "bg",       label: "Sky",                 type: "color", default: "#1a1a3a" },
      { key: "ground",   label: "Ground",              type: "color", default: "#333333" },
      { key: "player",   label: "Player",              type: "color", default: "#4af" },
      { key: "obstacle", label: "Obstacle",            type: "color", default: "#f44" },
      { key: "speed",    label: "Scroll speed (1-20)", type: "text",  default: "6" },
      { key: "spawn",    label: "Spawn rate",          type: "text",  default: "100" }
    ],
    config: function(cfg) {
      return {
        title: cfg.title,
        world: { w: 800, h: 600, bg: cfg.bg },
        slots: [
          { x: 100, y: 500, w: 40, h: 40, color: cfg.player },
          { x: 700, y: 480, w: 40, h: 60, color: cfg.obstacle }
        ],
        palette: [cfg.player, cfg.obstacle, cfg.ground]
      };
    },
    generate: function(cfg) {
      var speed = parseInt(cfg.speed) || 6;
      var spawnRate = parseInt(cfg.spawn) || 100;
      return [
        "const display = new Display();",
        "display.perform();",
        "display.start(800, 600);",
        "display.backgroundColor('" + cfg.bg + "');",
        "",
        "const ground = new Component(800, 60, '" + cfg.ground + "', 0, 540, 'rect');",
        "display.add(ground);",
        "",
        "const player = new Component(40, 40, '" + cfg.player + "', 100, 500, 'rect');",
        "display.add(player);",
        "",
        "const score = new Tctxt('20px','Arial','white',20,40,'left',false,'top','rgba(0,0,0,0.5)',10,4);",
        "score.setText('Tap to jump. Score: 0');",
        "display.add(score);",
        "",
        "let restartBtn = null;",
        "let restartLbl = null;",
        "",
        "const obstacles = [];",
        "let frame = 0;",
        "let vy = 0;",
        "let onGround = true;",
        "let points = 0;",
        "let gameOver = false;",
        "",
        "function rectHit(a, b) {",
        "  return a.x < b.x + b.width && a.x + a.width > b.x && a.y < b.y + b.height && a.y + a.height > b.y;",
        "}",
        "",
        "function spawn() {",
        "  const h = 40 + Math.floor(Math.random() * 40);",
        "  const o = new Component(40, h, '" + cfg.obstacle + "', 820, 540 - h, 'rect');",
        "  display.add(o);",
        "  obstacles.push(o);",
        "}",
        "",
        "function showRestart() {",
        "  restartBtn = new Component(200, 60, '#2563eb', 300, 300, 'rect');",
        "  restartLbl = new Tctxt('24px','Arial','white',400,330,'center',false,'middle');",
        "  restartLbl.setText('▶ PLAY AGAIN');",
        "  display.add(restartBtn); display.add(restartLbl);",
        "}",
        "",
        "function restart() {",
        "  if (restartBtn) { restartBtn.destroy(); restartBtn = null; }",
        "  if (restartLbl) { restartLbl.destroy(); restartLbl = null; }",
        "  for (let i = obstacles.length - 1; i >= 0; i--) {",
        "    obstacles[i].destroy();",
        "  }",
        "  obstacles.length = 0;",
        "  player.x = 100; player.y = 500;",
        "  vy = 0; onGround = true; points = 0; frame = 0;",
        "  gameOver = false;",
        "  score.setText('Tap to jump. Score: 0');",
        "}",
        "",
        "function update(dt) {",
        "  if (gameOver) {",
        "    const mx = display.x, my = display.y;",
        "    if (mx !== false && restartBtn &&",
        "        mx >= restartBtn.x && mx <= restartBtn.x + restartBtn.width &&",
        "        my >= restartBtn.y && my <= restartBtn.y + restartBtn.height) {",
        "      restart();",
        "    }",
        "    return;",
        "  }",
        "",
        "  frame++;",
        "  if (frame % " + spawnRate + " === 0) spawn();",
        "",
        "  const keyJump = display.keys[38] || display.keys[32] || display.keys[87];",
        "  const tapJump = display.x !== false;",
        "  if ((keyJump || tapJump) && onGround) {",
        "    vy = -13;",
        "    onGround = false;",
        "  }",
        "",
        "  vy += 40 * dt;",
        "  player.y += vy;",
        "",
        "  if (player.y >= 500) {",
        "    player.y = 500;",
        "    vy = 0;",
        "    onGround = true;",
        "  }",
        "",
        "  for (let i = obstacles.length - 1; i >= 0; i--) {",
        "    const o = obstacles[i];",
        "    o.x -= " + speed + ";",
        "    if (o.x < -60) {",
        "      o.destroy();",
        "      obstacles.splice(i, 1);",
        "      points += 5;",
        "      score.setText('Score: ' + points);",
        "    } else if (rectHit(player, o)) {",
        "      gameOver = true;",
        "      score.setText('Game Over! Score: ' + points);",
        "      showRestart();",
        "    }",
        "  }",
        "}"
      ].join("\n");
    }
  },

  shooter: {
    name: "Shooter",
    fields: [
      { key: "title",    label: "Title",             type: "text",  default: "Star Fight" },
      { key: "bg",       label: "Space",             type: "color", default: "#050510" },
      { key: "player",   label: "Ship",              type: "color", default: "#4af" },
      { key: "bullet",   label: "Bullet",            type: "color", default: "#fd3" },
      { key: "enemy",    label: "Enemy",             type: "color", default: "#f44" },
      { key: "speed",    label: "Move speed",        type: "text",  default: "320" },
      { key: "fireRate", label: "Fire rate (frames)",type: "text",  default: "12" },
      { key: "spawn",    label: "Enemy spawn",       type: "text",  default: "90" }
    ],
    config: function(cfg) {
      return {
        title: cfg.title,
        world: { w: 800, h: 600, bg: cfg.bg },
        slots: [
          { x: 380, y: 520, w: 40, h: 40, color: cfg.player },
          { x: 380, y: 300, w: 30, h: 30, color: cfg.enemy }
        ],
        palette: [cfg.player, cfg.bullet, cfg.enemy]
      };
    },
    generate: function(cfg) {
      var speed = parseInt(cfg.speed) || 320;
      var fireRate = parseInt(cfg.fireRate) || 12;
      var spawnRate = parseInt(cfg.spawn) || 90;
      return [
        "const display = new Display();",
        "display.perform();",
        "display.start(800, 600);",
        "display.backgroundColor('" + cfg.bg + "');",
        "",
        "const player = new Component(40, 40, '" + cfg.player + "', 380, 520, 'rect');",
        "display.add(player);",
        "",
        "const score = new Tctxt('20px','Arial','white',20,40,'left',false,'top','rgba(0,0,0,0.5)',10,4);",
        "score.setText('Score: 0');",
        "display.add(score);",
        "",
        "const BTN = 80;",
        "const BTN_Y = 500;",
        "function mkBtn(x, color) {",
        "  return new Component(BTN, BTN, color, x, BTN_Y, 'rect');",
        "}",
        "const btnL = mkBtn(20,  '#1a1a2e');",
        "const btnR = mkBtn(120, '#1a1a2e');",
        "const btnF = mkBtn(680, '#dc2626');",
        "const lblL = new Tctxt('36px','Arial','white',60,540,'center',false,'middle');",
        "const lblR = new Tctxt('36px','Arial','white',160,540,'center',false,'middle');",
        "const lblF = new Tctxt('16px','Arial','white',720,540,'center',false,'middle');",
        "lblL.setText('◀'); lblR.setText('▶'); lblF.setText('FIRE');",
        "display.add(btnL); display.add(btnR); display.add(btnF);",
        "display.add(lblL); display.add(lblR); display.add(lblF);",
        "",
        "function inBtn(b, x, y) {",
        "  return x >= b.x && x <= b.x + b.width && y >= b.y && y <= b.y + b.height;",
        "}",
        "",
        "let restartBtn = null;",
        "let restartLbl = null;",
        "",
        "const bullets = [];",
        "const enemies = [];",
        "let frame = 0;",
        "let points = 0;",
        "let gameOver = false;",
        "",
        "function rectHit(a, b) {",
        "  return a.x < b.x + b.width && a.x + a.width > b.x && a.y < b.y + b.height && a.y + a.height > b.y;",
        "}",
        "",
        "function showRestart() {",
        "  restartBtn = new Component(200, 60, '#2563eb', 300, 300, 'rect');",
        "  restartLbl = new Tctxt('24px','Arial','white',400,330,'center',false,'middle');",
        "  restartLbl.setText('▶ PLAY AGAIN');",
        "  display.add(restartBtn); display.add(restartLbl);",
        "}",
        "",
        "function restart() {",
        "  if (restartBtn) { restartBtn.destroy(); restartBtn = null; }",
        "  if (restartLbl) { restartLbl.destroy(); restartLbl = null; }",
        "  for (let i = bullets.length - 1; i >= 0; i--) bullets[i].destroy();",
        "  for (let i = enemies.length - 1; i >= 0; i--) enemies[i].destroy();",
        "  bullets.length = 0; enemies.length = 0;",
        "  player.x = 380; player.y = 520;",
        "  frame = 0; points = 0; gameOver = false;",
        "  score.setText('Score: 0');",
        "}",
        "",
        "function update(dt) {",
        "  if (gameOver) {",
        "    const mx = display.x, my = display.y;",
        "    if (mx !== false && restartBtn &&",
        "        mx >= restartBtn.x && mx <= restartBtn.x + restartBtn.width &&",
        "        my >= restartBtn.y && my <= restartBtn.y + restartBtn.height) {",
        "      restart();",
        "    }",
        "    return;",
        "  }",
        "",
        "  frame++;",
        "  const sp = " + speed + ";",
        "",
        "  const mx = display.x, my = display.y;",
        "  const touchingL = mx !== false && inBtn(btnL, mx, my);",
        "  const touchingR = mx !== false && inBtn(btnR, mx, my);",
        "  const touchingF = mx !== false && inBtn(btnF, mx, my);",
        "",
        "  if (display.keys[37] || display.keys[65] || touchingL) player.x -= sp * dt;",
        "  if (display.keys[39] || display.keys[68] || touchingR) player.x += sp * dt;",
        "",
        "  if (player.x < 0) player.x = 0;",
        "  if (player.x + player.width > 800) player.x = 800 - player.width;",
        "",
        "  const keyFire = display.keys[32] || display.keys[38];",
        "  if ((keyFire || touchingF) && frame % " + fireRate + " === 0) {",
        "    const b = new Component(6, 14, '" + cfg.bullet + "', player.x + 17, player.y - 10, 'rect');",
        "    display.add(b);",
        "    bullets.push(b);",
        "  }",
        "",
        "  for (let i = bullets.length - 1; i >= 0; i--) {",
        "    const b = bullets[i];",
        "    b.y -= 12;",
        "    if (b.y < -20) { b.destroy(); bullets.splice(i, 1); }",
        "  }",
        "",
        "  if (frame % " + spawnRate + " === 0) {",
        "    const e = new Component(36, 36, '" + cfg.enemy + "', 20 + Math.random() * 740, -40, 'rect');",
        "    display.add(e);",
        "    enemies.push(e);",
        "  }",
        "",
        "  for (let i = enemies.length - 1; i >= 0; i--) {",
        "    const e = enemies[i];",
        "    e.y += 2;",
        "",
        "    if (e.y > 620) { e.destroy(); enemies.splice(i, 1); continue; }",
        "",
        "    if (rectHit(player, e)) {",
        "      gameOver = true;",
        "      score.setText('Game Over! Score: ' + points);",
        "      showRestart();",
        "    }",
        "",
        "    for (let j = bullets.length - 1; j >= 0; j--) {",
        "      if (rectHit(bullets[j], e)) {",
        "        bullets[j].destroy(); bullets.splice(j, 1);",
        "        e.destroy(); enemies.splice(i, 1);",
        "        points += 10;",
        "        score.setText('Score: ' + points);",
        "        break;",
        "      }",
        "    }",
        "  }",
        "}"
      ].join("\n");
    }
  },

  clicker: {
    name: "Clicker",
    fields: [
      { key: "title",    label: "Title",              type: "text",  default: "Click Rush" },
      { key: "bg",       label: "Background",         type: "color", default: "#0d0d2a" },
      { key: "target",   label: "Target",             type: "color", default: "#4af" },
      { key: "size",     label: "Target size (px)",   type: "text",  default: "60" },
      { key: "lifetime", label: "Lifetime (frames)",  type: "text",  default: "90" },
      { key: "time",     label: "Game time (secs)",   type: "text",  default: "30" }
    ],
    config: function(cfg) {
      return {
        title: cfg.title,
        world: { w: 800, h: 600, bg: cfg.bg },
        slots: [
          { x: 370, y: 270, w: 60, h: 60, color: cfg.target }
        ],
        palette: [cfg.target]
      };
    },
    generate: function(cfg) {
      var size = parseInt(cfg.size) || 60;
      var life = parseInt(cfg.lifetime) || 90;
      var totalTime = parseInt(cfg.time) || 30;
      return [
        "const display = new Display();",
        "display.perform();",
        "display.start(800, 600);",
        "display.backgroundColor('" + cfg.bg + "');",
        "",
        "const score = new Tctxt('20px','Arial','white',20,40,'left',false,'top','rgba(0,0,0,0.5)',10,4);",
        "score.setText('Tap the square. Score: 0  Time: " + totalTime + "');",
        "display.add(score);",
        "",
        "let target = null;",
        "let points = 0;",
        "let timeLeft = " + totalTime + ";",
        "let timer = 0;",
        "let spawnTimer = 0;",
        "let gameOver = false;",
        "let mouseWasDown = false;",
        "",
        "let restartBtn = null;",
        "let restartLbl = null;",
        "",
        "function spawnTarget() {",
        "  if (target) target.destroy();",
        "  const s = " + size + ";",
        "  const x = Math.random() * (800 - s);",
        "  const y = 80 + Math.random() * (520 - s);",
        "  target = new Component(s, s, '" + cfg.target + "', x, y, 'rect');",
        "  display.add(target);",
        "}",
        "",
        "function showRestart() {",
        "  restartBtn = new Component(200, 60, '#2563eb', 300, 300, 'rect');",
        "  restartLbl = new Tctxt('24px','Arial','white',400,330,'center',false,'middle');",
        "  restartLbl.setText('▶ PLAY AGAIN');",
        "  display.add(restartBtn); display.add(restartLbl);",
        "}",
        "",
        "function restart() {",
        "  if (restartBtn) { restartBtn.destroy(); restartBtn = null; }",
        "  if (restartLbl) { restartLbl.destroy(); restartLbl = null; }",
        "  if (target) { target.destroy(); target = null; }",
        "  points = 0; timeLeft = " + totalTime + "; timer = 0; spawnTimer = 0;",
        "  gameOver = false;",
        "  score.setText('Tap the square. Score: 0  Time: " + totalTime + "');",
        "  spawnTarget();",
        "}",
        "",
        "spawnTarget();",
        "",
        "function update(dt) {",
        "  if (gameOver) {",
        "    const mx = display.x, my = display.y;",
        "    if (mx !== false && restartBtn &&",
        "        mx >= restartBtn.x && mx <= restartBtn.x + restartBtn.width &&",
        "        my >= restartBtn.y && my <= restartBtn.y + restartBtn.height) {",
        "      restart();",
        "    }",
        "    return;",
        "  }",
        "",
        "  timer += dt;",
        "  if (timer >= 1) {",
        "    timer -= 1;",
        "    timeLeft--;",
        "    score.setText('Score: ' + points + '  Time: ' + timeLeft);",
        "    if (timeLeft <= 0) {",
        "      gameOver = true;",
        "      if (target) target.destroy();",
        "      score.setText('Game Over! Final Score: ' + points);",
        "      showRestart();",
        "      return;",
        "    }",
        "  }",
        "",
        "  spawnTimer++;",
        "  if (!target || spawnTimer > " + life + ") {",
        "    spawnTarget();",
        "    spawnTimer = 0;",
        "  }",
        "",
        "  if (display.x !== false && !mouseWasDown && target) {",
        "    const mx = display.x, my = display.y;",
        "    if (mx >= target.x && mx <= target.x + target.width && my >= target.y && my <= target.y + target.height) {",
        "      points += 10;",
        "      score.setText('Score: ' + points + '  Time: ' + timeLeft);",
        "      target.destroy();",
        "      target = null;",
        "      spawnTarget();",
        "      spawnTimer = 0;",
        "    }",
        "    mouseWasDown = true;",
        "  }",
        "  if (display.x === false) mouseWasDown = false;",
        "}"
      ].join("\n");
    }
  },
breakout: {
  name: "Breakout",
  fields: [
    { key: "title",    label: "Title",           type: "text",  default: "Brick Buster" },
    { key: "bg",       label: "Background",      type: "color", default: "#0d0d2a" },
    { key: "paddle",   label: "Paddle",          type: "color", default: "#4af" },
    { key: "ball",     label: "Ball",            type: "color", default: "#ffffff" },
    { key: "brickA",   label: "Brick (top row)", type: "color", default: "#ec4899" },
    { key: "brickB",   label: "Brick (bottom)",  type: "color", default: "#22d3ee" },
    { key: "speed",    label: "Ball speed",      type: "text",  default: "5" }
  ],
  config: function(cfg) {
    return {
      title: cfg.title,
      world: { w: 800, h: 600, bg: cfg.bg },
      slots: [
        { x: 340, y: 540, w: 120, h: 20, color: cfg.paddle },
        { x: 400, y: 400, w: 16,  h: 16, color: cfg.ball },
        { x: 100, y: 60,  w: 76,  h: 20, color: cfg.brickA }
      ],
      palette: [cfg.paddle, cfg.ball, cfg.brickA, cfg.brickB]
    };
  },
  generate: function(cfg) {
    var speed = parseInt(cfg.speed) || 5;
    return [
      "const display = new Display();",
      "display.perform();",
      "display.start(800, 600);",
      "display.backgroundColor('" + cfg.bg + "');",
      "",
      "const paddle = new Component(120, 20, '" + cfg.paddle + "', 340, 540, 'rect');",
      "display.add(paddle);",
      "",
      "const ball = new Component(16, 16, '" + cfg.ball + "', 400, 400, 'rect');",
      "display.add(ball);",
      "let vx = " + speed + ", vy = -" + speed + ";",
      "",
      "const score = new Tctxt('20px','Arial','white',20,40,'left',false,'top','rgba(0,0,0,0.5)',10,4);",
      "score.setText('Score: 0');",
      "display.add(score);",
      "",
      "const bricks = [];",
      "const COLS = 8, ROWS = 5;",
      "const BW = 86, BH = 22, GAP = 6;",
      "const startX = (800 - COLS * BW - (COLS - 1) * GAP) / 2;",
      "for (let r = 0; r < ROWS; r++) {",
      "  const color = r < 2 ? '" + cfg.brickA + "' : '" + cfg.brickB + "';",
      "  for (let c = 0; c < COLS; c++) {",
      "    const b = new Component(BW, BH, color, startX + c * (BW + GAP), 70 + r * (BH + GAP), 'rect');",
      "    display.add(b);",
      "    bricks.push(b);",
      "  }",
      "}",
      "",
      "let points = 0;",
      "let gameOver = false;",
      "let won = false;",
      "let restartBtn = null;",
      "let restartLbl = null;",
      "",
      "function rectHit(a, b) {",
      "  return a.x < b.x + b.width && a.x + a.width > b.x && a.y < b.y + b.height && a.y + a.height > b.y;",
      "}",
      "",
      "function showRestart(msg) {",
      "  restartBtn = new Component(220, 60, '#2563eb', 290, 300, 'rect');",
      "  restartLbl = new Tctxt('22px','Arial','white',400,330,'center',false,'middle');",
      "  restartLbl.setText(msg);",
      "  display.add(restartBtn); display.add(restartLbl);",
      "}",
      "",
      "function restart() {",
      "  if (restartBtn) { restartBtn.destroy(); restartBtn = null; }",
      "  if (restartLbl) { restartLbl.destroy(); restartLbl = null; }",
      "  for (const b of bricks) b.destroy();",
      "  bricks.length = 0;",
      "  for (let r = 0; r < ROWS; r++) {",
      "    const color = r < 2 ? '" + cfg.brickA + "' : '" + cfg.brickB + "';",
      "    for (let c = 0; c < COLS; c++) {",
      "      const b = new Component(BW, BH, color, startX + c * (BW + GAP), 70 + r * (BH + GAP), 'rect');",
      "      display.add(b);",
      "      bricks.push(b);",
      "    }",
      "  }",
      "  ball.x = 400; ball.y = 400;",
      "  vx = " + speed + "; vy = -" + speed + ";",
      "  points = 0; gameOver = false; won = false;",
      "  score.setText('Score: 0');",
      "}",
      "",
      "const BTN = 100;",
      "const btnL = new Component(BTN, BTN, '#1a1a2e', 20, 480, 'rect');",
      "const btnR = new Component(BTN, BTN, '#1a1a2e', 680, 480, 'rect');",
      "display.add(btnL); display.add(btnR);",
      "",
      "function inBtn(b, x, y) {",
      "  return x >= b.x && x <= b.x + b.width && y >= b.y && y <= b.y + b.height;",
      "}",
      "",
      "function update(dt) {",
      "  if (gameOver || won) {",
      "    const mx = display.x, my = display.y;",
      "    if (mx !== false && restartBtn &&",
      "        mx >= restartBtn.x && mx <= restartBtn.x + restartBtn.width &&",
      "        my >= restartBtn.y && my <= restartBtn.y + restartBtn.height) restart();",
      "    return;",
      "  }",
      "",
      "  const mx = display.x, my = display.y;",
      "  const padSpeed = 480 * dt;",
      "  if (display.keys[37] || display.keys[65] || (mx !== false && inBtn(btnL, mx, my))) paddle.x -= padSpeed;",
      "  if (display.keys[39] || display.keys[68] || (mx !== false && inBtn(btnR, mx, my))) paddle.x += padSpeed;",
      "  if (paddle.x < 0) paddle.x = 0;",
      "  if (paddle.x + paddle.width > 800) paddle.x = 800 - paddle.width;",
      "",
      "  ball.x += vx;",
      "  ball.y += vy;",
      "",
      "  if (ball.x <= 0 || ball.x + ball.width >= 800) vx = -vx;",
      "  if (ball.y <= 0) vy = -vy;",
      "",
      "  if (vy > 0 && rectHit(ball, paddle)) {",
      "    vy = -vy;",
      "    const hit = (ball.x + ball.width / 2 - (paddle.x + paddle.width / 2)) / (paddle.width / 2);",
      "    vx = hit * " + speed + ";",
      "  }",
      "",
      "  if (ball.y > 600) {",
      "    gameOver = true;",
      "    score.setText('Game Over! Score: ' + points);",
      "    showRestart('▶ PLAY AGAIN');",
      "    return;",
      "  }",
      "",
      "  for (let i = bricks.length - 1; i >= 0; i--) {",
      "    if (rectHit(ball, bricks[i])) {",
      "      bricks[i].destroy();",
      "      bricks.splice(i, 1);",
      "      vy = -vy;",
      "      points += 10;",
      "      score.setText('Score: ' + points);",
      "      break;",
      "    }",
      "  }",
      "",
      "  if (bricks.length === 0) {",
      "    won = true;",
      "    score.setText('You win! Score: ' + points);",
      "    showRestart('▶ PLAY AGAIN');",
      "  }",
      "}"
    ].join("\n");
  }
},

flappy: {
  name: "Flappy",
  fields: [
    { key: "title",  label: "Title",         type: "text",  default: "Flappy Square" },
    { key: "bg",     label: "Sky",           type: "color", default: "#0d0d2a" },
    { key: "player", label: "Player",        type: "color", default: "#fd3" },
    { key: "pipe",   label: "Pipes",         type: "color", default: "#4f8" },
    { key: "gravity",label: "Gravity (1-4)", type: "text",  default: "2" },
    { key: "flap",   label: "Flap force",    type: "text",  default: "9" },
    { key: "speed",  label: "Scroll speed",  type: "text",  default: "3" }
  ],
  config: function(cfg) {
    return {
      title: cfg.title,
      world: { w: 800, h: 600, bg: cfg.bg },
      slots: [
        { x: 120, y: 280, w: 40, h: 40, color: cfg.player },
        { x: 700, y: 100, w: 70, h: 220, color: cfg.pipe }
      ],
      palette: [cfg.player, cfg.pipe]
    };
  },
  generate: function(cfg) {
    var gravity = parseFloat(cfg.gravity) || 2;
    var flap = parseFloat(cfg.flap) || 9;
    var speed = parseInt(cfg.speed) || 3;
    return [
      "const display = new Display();",
      "display.perform();",
      "display.start(800, 600);",
      "display.backgroundColor('" + cfg.bg + "');",
      "",
      "const player = new Component(40, 40, '" + cfg.player + "', 120, 280, 'rect');",
      "player.changeAngle = false;",
      "display.add(player);",
      "",
      "const score = new Tctxt('22px','Arial','white',400,60,'center',false,'top','rgba(0,0,0,0.5)',14,6);",
      "score.setText('Tap to flap. Score: 0');",
      "display.add(score);",
      "",
      "const pipes = [];",
      "let vy = 0;",
      "let points = 0;",
      "let frame = 0;",
      "let gameOver = false;",
      "let restartBtn = null;",
      "let restartLbl = null;",
      "",
      "const GAP = 180;",
      "const PIPE_W = 70;",
      "",
      "function rectHit(a, b) {",
      "  return a.x < b.x + b.width && a.x + a.width > b.x && a.y < b.y + b.height && a.y + a.height > b.y;",
      "}",
      "",
      "function spawnPipe() {",
      "  const topH = 80 + Math.random() * 240;",
      "  const bottomY = topH + GAP;",
      "  const bottomH = 600 - bottomY;",
      "  const top = new Component(PIPE_W, topH, '" + cfg.pipe + "', 820, 0, 'rect');",
      "  const bot = new Component(PIPE_W, bottomH, '" + cfg.pipe + "', 820, bottomY, 'rect');",
      "  top.scored = false;",
      "  top.isTop = true;",
      "  bot.isTop = false;",
      "  display.add(top); display.add(bot);",
      "  pipes.push(top); pipes.push(bot);",
      "}",
      "",
      "function showRestart() {",
      "  restartBtn = new Component(220, 60, '#2563eb', 290, 280, 'rect');",
      "  restartLbl = new Tctxt('22px','Arial','white',400,310,'center',false,'middle');",
      "  restartLbl.setText('▶ PLAY AGAIN');",
      "  display.add(restartBtn); display.add(restartLbl);",
      "}",
      "",
      "function restart() {",
      "  if (restartBtn) { restartBtn.destroy(); restartBtn = null; }",
      "  if (restartLbl) { restartLbl.destroy(); restartLbl = null; }",
      "  for (const p of pipes) p.destroy();",
      "  pipes.length = 0;",
      "  player.x = 120; player.y = 280;",
      "  vy = 0; points = 0; frame = 0; gameOver = false;",
      "  score.setText('Tap to flap. Score: 0');",
      "}",
      "",
      "function update(dt) {",
      "  if (gameOver) {",
      "    const mx = display.x, my = display.y;",
      "    if (mx !== false && restartBtn &&",
      "        mx >= restartBtn.x && mx <= restartBtn.x + restartBtn.width &&",
      "        my >= restartBtn.y && my <= restartBtn.y + restartBtn.height) restart();",
      "    return;",
      "  }",
      "",
      "  frame++;",
      "  if (frame % 90 === 0) spawnPipe();",
      "",
      "  const keyFlap = display.keys[32] || display.keys[38] || display.keys[87];",
      "  const tapFlap = display.x !== false;",
      "  if (keyFlap || tapFlap) vy = -" + flap + ";",
      "",
      "  vy += " + gravity + ";",
      "  player.y += vy;",
      "",
      "  if (player.y < 0) { player.y = 0; vy = 0; }",
      "  if (player.y + player.height > 600) {",
      "    gameOver = true;",
      "    score.setText('Game Over! Score: ' + points);",
      "    showRestart();",
      "    return;",
      "  }",
      "",
      "  for (let i = pipes.length - 1; i >= 0; i--) {",
      "    const p = pipes[i];",
      "    p.x -= " + speed + ";",
      "",
      "    if (p.x + p.width < 0) {",
      "      p.destroy();",
      "      pipes.splice(i, 1);",
      "      continue;",
      "    }",
      "",
      "    if (rectHit(player, p)) {",
      "      gameOver = true;",
      "      score.setText('Game Over! Score: ' + points);",
      "      showRestart();",
      "      return;",
      "    }",
      "",
      "    if (p.isTop && !p.scored && p.x + p.width < player.x) {",
      "      p.scored = true;",
      "      points++;",
      "      score.setText('Score: ' + points);",
      "    }",
      "  }",
      "}"
    ].join("\n");
  }
},

snake: {
  name: "Snake",
  fields: [
    { key: "title",    label: "Title",        type: "text",  default: "Snake" },
    { key: "bg",       label: "Background",   type: "color", default: "#0d0d2a" },
    { key: "snake",    label: "Snake body",   type: "color", default: "#4f8" },
    { key: "head",     label: "Snake head",   type: "color", default: "#7fffb2" },
    { key: "food",     label: "Food",         type: "color", default: "#f44" },
    { key: "cell",     label: "Cell size (px)",type: "text",  default: "30" },
    { key: "tickRate", label: "Speed (frames)",type: "text",  default: "8" }
  ],
  config: function(cfg) {
    return {
      title: cfg.title,
      world: { w: 800, h: 600, bg: cfg.bg },
      slots: [
        { x: 400, y: 300, w: 30, h: 30, color: cfg.head },
        { x: 340, y: 300, w: 30, h: 30, color: cfg.snake },
        { x: 600, y: 300, w: 30, h: 30, color: cfg.food }
      ],
      palette: [cfg.snake, cfg.head, cfg.food]
    };
  },
  generate: function(cfg) {
    var cell = parseInt(cfg.cell) || 30;
    var tick = parseInt(cfg.tickRate) || 8;
    return [
      "const display = new Display();",
      "display.perform();",
      "display.start(800, 600);",
      "display.backgroundColor('" + cfg.bg + "');",
      "",
      "const CELL = " + cell + ";",
      "const COLS = Math.floor(800 / CELL);",
      "const ROWS = Math.floor(600 / CELL);",
      "",
      "const score = new Tctxt('20px','Arial','white',20,40,'left',false,'top','rgba(0,0,0,0.5)',10,4);",
      "score.setText('Score: 0');",
      "display.add(score);",
      "",
      "let snake = [{ x: 10, y: 10 }, { x: 9, y: 10 }, { x: 8, y: 10 }];",
      "let dir = { x: 1, y: 0 };",
      "let nextDir = { x: 1, y: 0 };",
      "let food = { x: 20, y: 10 };",
      "let cells = [];",
      "let foodComp = null;",
      "let frame = 0;",
      "let points = 0;",
      "let gameOver = false;",
      "let restartBtn = null;",
      "let restartLbl = null;",
      "",
      "function makeCell(color) {",
      "  const c = new Component(CELL - 2, CELL - 2, color, 0, 0, 'rect');",
      "  c.changeAngle = false;",
      "  display.add(c);",
      "  return c;",
      "}",
      "",
      "function draw() {",
      "  while (cells.length < snake.length) cells.push(makeCell('" + cfg.snake + "'));",
      "  for (let i = 0; i < snake.length; i++) {",
      "    const s = snake[i];",
      "    const c = cells[i];",
      "    c.x = s.x * CELL + 1;",
      "    c.y = s.y * CELL + 1;",
      "    c.color = i === 0 ? '" + cfg.head + "' : '" + cfg.snake + "';",
      "  }",
      "  for (let i = snake.length; i < cells.length; i++) cells[i].x = -100;",
      "}",
      "",
      "function placeFood() {",
      "  while (true) {",
      "    food.x = Math.floor(Math.random() * COLS);",
      "    food.y = Math.floor(Math.random() * ROWS);",
      "    if (!snake.some(s => s.x === food.x && s.y === food.y)) break;",
      "  }",
      "  if (foodComp) foodComp.destroy();",
      "  foodComp = makeCell('" + cfg.food + "');",
      "  foodComp.x = food.x * CELL + 1;",
      "  foodComp.y = food.y * CELL + 1;",
      "}",
      "",
      "function showRestart() {",
      "  restartBtn = new Component(220, 60, '#2563eb', 290, 280, 'rect');",
      "  restartLbl = new Tctxt('22px','Arial','white',400,310,'center',false,'middle');",
      "  restartLbl.setText('▶ PLAY AGAIN');",
      "  display.add(restartBtn); display.add(restartLbl);",
      "}",
      "",
      "function restart() {",
      "  if (restartBtn) { restartBtn.destroy(); restartBtn = null; }",
      "  if (restartLbl) { restartLbl.destroy(); restartLbl = null; }",
      "  for (const c of cells) c.destroy();",
      "  cells.length = 0;",
      "  if (foodComp) { foodComp.destroy(); foodComp = null; }",
      "  snake = [{ x: 10, y: 10 }, { x: 9, y: 10 }, { x: 8, y: 10 }];",
      "  dir = { x: 1, y: 0 }; nextDir = { x: 1, y: 0 };",
      "  points = 0; frame = 0; gameOver = false;",
      "  score.setText('Score: 0');",
      "  placeFood();",
      "  draw();",
      "}",
      "",
      "function setDir(x, y) {",
      "  if (dir.x === -x && dir.y === -y) return;",
      "  nextDir = { x: x, y: y };",
      "}",
      "",
      "const btnSize = 80;",
      "const btnUp = new Component(btnSize, btnSize, '#1a1a2e', 360, 460, 'rect');",
      "const btnDown = new Component(btnSize, btnSize, '#1a1a2e', 360, 560, 'rect');",
      "const btnLeft = new Component(btnSize, btnSize, '#1a1a2e', 260, 510, 'rect');",
      "const btnRight = new Component(btnSize, btnSize, '#1a1a2e', 460, 510, 'rect');",
      "display.add(btnUp); display.add(btnDown); display.add(btnLeft); display.add(btnRight);",
      "",
      "function inBtn(b, x, y) {",
      "  return x >= b.x && x <= b.x + b.width && y >= b.y && y <= b.y + b.height;",
      "}",
      "",
      "placeFood();",
      "draw();",
      "",
      "function update(dt) {",
      "  if (gameOver) {",
      "    const mx = display.x, my = display.y;",
      "    if (mx !== false && restartBtn &&",
      "        mx >= restartBtn.x && mx <= restartBtn.x + restartBtn.width &&",
      "        my >= restartBtn.y && my <= restartBtn.y + restartBtn.height) restart();",
      "    return;",
      "  }",
      "",
      "  const mx = display.x, my = display.y;",
      "  if (display.keys[38] || display.keys[87] || (mx !== false && inBtn(btnUp, mx, my))) setDir(0, -1);",
      "  if (display.keys[40] || display.keys[83] || (mx !== false && inBtn(btnDown, mx, my))) setDir(0, 1);",
      "  if (display.keys[37] || display.keys[65] || (mx !== false && inBtn(btnLeft, mx, my))) setDir(-1, 0);",
      "  if (display.keys[39] || display.keys[68] || (mx !== false && inBtn(btnRight, mx, my))) setDir(1, 0);",
      "",
      "  frame++;",
      "  if (frame < " + tick + ") return;",
      "  frame = 0;",
      "",
      "  dir = nextDir;",
      "  const head = { x: snake[0].x + dir.x, y: snake[0].y + dir.y };",
      "",
      "  if (head.x < 0 || head.x >= COLS || head.y < 0 || head.y >= ROWS ||",
      "      snake.some(s => s.x === head.x && s.y === head.y)) {",
      "    gameOver = true;",
      "    score.setText('Game Over! Score: ' + points);",
      "    showRestart();",
      "    return;",
      "  }",
      "",
      "  snake.unshift(head);",
      "  if (head.x === food.x && head.y === food.y) {",
      "    points += 10;",
      "    score.setText('Score: ' + points);",
      "    placeFood();",
      "  } else {",
      "    snake.pop();",
      "  }",
      "  draw();",
      "}"
    ].join("\n");
  }
},

catch: {
  name: "Catch",
  fields: [
    { key: "title",  label: "Title",         type: "text",  default: "Catch It" },
    { key: "bg",     label: "Background",    type: "color", default: "#0d0d2a" },
    { key: "basket", label: "Basket",        type: "color", default: "#4af" },
    { key: "fruit",  label: "Fruit",         type: "color", default: "#4f8" },
    { key: "bomb",   label: "Bomb",          type: "color", default: "#f44" },
    { key: "speed",  label: "Basket speed",  type: "text",  default: "420" },
    { key: "fall",   label: "Fall speed",    type: "text",  default: "4" },
    { key: "rate",   label: "Spawn (frames)",type: "text",  default: "45" }
  ],
  config: function(cfg) {
    return {
      title: cfg.title,
      world: { w: 800, h: 600, bg: cfg.bg },
      slots: [
        { x: 350, y: 540, w: 100, h: 30, color: cfg.basket },
        { x: 300, y: 200, w: 28, h: 28, color: cfg.fruit },
        { x: 500, y: 200, w: 28, h: 28, color: cfg.bomb }
      ],
      palette: [cfg.basket, cfg.fruit, cfg.bomb]
    };
  },
  generate: function(cfg) {
    var speed = parseInt(cfg.speed) || 420;
    var fall = parseInt(cfg.fall) || 4;
    var rate = parseInt(cfg.rate) || 45;
    return [
      "const display = new Display();",
      "display.perform();",
      "display.start(800, 600);",
      "display.backgroundColor('" + cfg.bg + "');",
      "",
      "const basket = new Component(100, 30, '" + cfg.basket + "', 350, 540, 'rect');",
      "display.add(basket);",
      "",
      "const score = new Tctxt('20px','Arial','white',20,40,'left',false,'top','rgba(0,0,0,0.5)',10,4);",
      "score.setText('Score: 0  Lives: 3');",
      "display.add(score);",
      "",
      "const items = [];",
      "let frame = 0;",
      "let points = 0;",
      "let lives = 3;",
      "let gameOver = false;",
      "let restartBtn = null;",
      "let restartLbl = null;",
      "",
      "function rectHit(a, b) {",
      "  return a.x < b.x + b.width && a.x + a.width > b.x && a.y < b.y + b.height && a.y + a.height > b.y;",
      "}",
      "",
      "function spawn() {",
      "  const isBomb = Math.random() < 0.25;",
      "  const x = 20 + Math.random() * 740;",
      "  const color = isBomb ? '" + cfg.bomb + "' : '" + cfg.fruit + "';",
      "  const it = new Component(28, 28, color, x, -30, 'rect');",
      "  it.isBomb = isBomb;",
      "  display.add(it);",
      "  items.push(it);",
      "}",
      "",
      "function showRestart() {",
      "  restartBtn = new Component(220, 60, '#2563eb', 290, 280, 'rect');",
      "  restartLbl = new Tctxt('22px','Arial','white',400,310,'center',false,'middle');",
      "  restartLbl.setText('▶ PLAY AGAIN');",
      "  display.add(restartBtn); display.add(restartLbl);",
      "}",
      "",
      "function restart() {",
      "  if (restartBtn) { restartBtn.destroy(); restartBtn = null; }",
      "  if (restartLbl) { restartLbl.destroy(); restartLbl = null; }",
      "  for (const it of items) it.destroy();",
      "  items.length = 0;",
      "  basket.x = 350;",
      "  points = 0; lives = 3; frame = 0; gameOver = false;",
      "  score.setText('Score: 0  Lives: 3');",
      "}",
      "",
      "const btnL = new Component(100, 100, '#1a1a2e', 20, 480, 'rect');",
      "const btnR = new Component(100, 100, '#1a1a2e', 680, 480, 'rect');",
      "display.add(btnL); display.add(btnR);",
      "",
      "function inBtn(b, x, y) {",
      "  return x >= b.x && x <= b.x + b.width && y >= b.y && y <= b.y + b.height;",
      "}",
      "",
      "function update(dt) {",
      "  if (gameOver) {",
      "    const mx = display.x, my = display.y;",
      "    if (mx !== false && restartBtn &&",
      "        mx >= restartBtn.x && mx <= restartBtn.x + restartBtn.width &&",
      "        my >= restartBtn.y && my <= restartBtn.y + restartBtn.height) restart();",
      "    return;",
      "  }",
      "",
      "  frame++;",
      "  if (frame % " + rate + " === 0) spawn();",
      "",
      "  const mx = display.x, my = display.y;",
      "  const sp = " + speed + " * dt;",
      "  if (display.keys[37] || display.keys[65] || (mx !== false && inBtn(btnL, mx, my))) basket.x -= sp;",
      "  if (display.keys[39] || display.keys[68] || (mx !== false && inBtn(btnR, mx, my))) basket.x += sp;",
      "  if (basket.x < 0) basket.x = 0;",
      "  if (basket.x + basket.width > 800) basket.x = 800 - basket.width;",
      "",
      "  for (let i = items.length - 1; i >= 0; i--) {",
      "    const it = items[i];",
      "    it.y += " + fall + ";",
      "",
      "    if (it.y > 620) {",
      "      it.destroy();",
      "      items.splice(i, 1);",
      "      if (!it.isBomb) {",
      "        lives--;",
      "        score.setText('Score: ' + points + '  Lives: ' + lives);",
      "        if (lives <= 0) {",
      "          gameOver = true;",
      "          score.setText('Game Over! Score: ' + points);",
      "          showRestart();",
      "          return;",
      "        }",
      "      }",
      "      continue;",
      "    }",
      "",
      "    if (rectHit(it, basket)) {",
      "      it.destroy();",
      "      items.splice(i, 1);",
      "      if (it.isBomb) {",
      "        lives--;",
      "        score.setText('Score: ' + points + '  Lives: ' + lives);",
      "        if (lives <= 0) {",
      "          gameOver = true;",
      "          score.setText('Game Over! Score: ' + points);",
      "          showRestart();",
      "          return;",
      "        }",
      "      } else {",
      "        points += 10;",
      "        score.setText('Score: ' + points + '  Lives: ' + lives);",
      "      }",
      "    }",
      "  }",
      "}"
    ].join("\n");
  }
},

dodge: {
  name: "Dodge",
  fields: [
    { key: "title",   label: "Title",          type: "text",  default: "Dodge!" },
    { key: "bg",      label: "Background",     type: "color", default: "#0d0d2a" },
    { key: "player",  label: "Player",         type: "color", default: "#4af" },
    { key: "wall",    label: "Wall",           type: "color", default: "#f44" },
    { key: "speed",   label: "Move speed",     type: "text",  default: "380" },
    { key: "rate",    label: "Spawn (frames)", type: "text",  default: "35" }
  ],
  config: function(cfg) {
    return {
      title: cfg.title,
      world: { w: 800, h: 600, bg: cfg.bg },
      slots: [
        { x: 380, y: 280, w: 40, h: 40, color: cfg.player },
        { x: 0, y: 0, w: 120, h: 120, color: cfg.wall }
      ],
      palette: [cfg.player, cfg.wall]
    };
  },
  generate: function(cfg) {
    var speed = parseInt(cfg.speed) || 380;
    var rate = parseInt(cfg.rate) || 35;
    return [
      "const display = new Display();",
      "display.perform();",
      "display.start(800, 600);",
      "display.backgroundColor('" + cfg.bg + "');",
      "",
      "const player = new Component(40, 40, '" + cfg.player + "', 380, 280, 'rect');",
      "player.changeAngle = false;",
      "display.add(player);",
      "",
      "const score = new Tctxt('20px','Arial','white',20,40,'left',false,'top','rgba(0,0,0,0.5)',10,4);",
      "score.setText('Survive! Time: 0');",
      "display.add(score);",
      "",
      "const blocks = [];",
      "let frame = 0;",
      "let timeAlive = 0;",
      "let timer = 0;",
      "let gameOver = false;",
      "let restartBtn = null;",
      "let restartLbl = null;",
      "",
      "function rectHit(a, b) {",
      "  return a.x < b.x + b.width && a.x + a.width > b.x && a.y < b.y + b.height && a.y + a.height > b.y;",
      "}",
      "",
      "function spawnWave() {",
      "  const fromTop = Math.random() < 0.5;",
      "  const size = 60 + Math.random() * 60;",
      "  let b;",
      "  if (fromTop) {",
      "    b = new Component(size, size, '" + cfg.wall + "', Math.random() * (800 - size), -size, 'rect');",
      "    b.vy = 2 + Math.random() * 3;",
      "    b.vx = 0;",
      "  } else {",
      "    b = new Component(size, size, '" + cfg.wall + "', Math.random() < 0.5 ? -size : 800, Math.random() * 500, 'rect');",
      "    b.vx = (b.x < 0 ? 1 : -1) * (2 + Math.random() * 3);",
      "    b.vy = 0;",
      "  }",
      "  b.changeAngle = false;",
      "  display.add(b);",
      "  blocks.push(b);",
      "}",
      "",
      "function showRestart() {",
      "  restartBtn = new Component(220, 60, '#2563eb', 290, 280, 'rect');",
      "  restartLbl = new Tctxt('22px','Arial','white',400,310,'center',false,'middle');",
      "  restartLbl.setText('▶ PLAY AGAIN');",
      "  display.add(restartBtn); display.add(restartLbl);",
      "}",
      "",
      "function restart() {",
      "  if (restartBtn) { restartBtn.destroy(); restartBtn = null; }",
      "  if (restartLbl) { restartLbl.destroy(); restartLbl = null; }",
      "  for (const b of blocks) b.destroy();",
      "  blocks.length = 0;",
      "  player.x = 380; player.y = 280;",
      "  timeAlive = 0; timer = 0; frame = 0; gameOver = false;",
      "  score.setText('Survive! Time: 0');",
      "}",
      "",
      "function update(dt) {",
      "  if (gameOver) {",
      "    const mx = display.x, my = display.y;",
      "    if (mx !== false && restartBtn &&",
      "        mx >= restartBtn.x && mx <= restartBtn.x + restartBtn.width &&",
      "        my >= restartBtn.y && my <= restartBtn.y + restartBtn.height) restart();",
      "    return;",
      "  }",
      "",
      "  frame++;",
      "  timer += dt;",
      "  if (timer >= 1) { timer -= 1; timeAlive++; score.setText('Survive! Time: ' + timeAlive); }",
      "",
      "  const spawnEvery = Math.max(12, " + rate + " - Math.floor(timeAlive / 3));",
      "  if (frame % spawnEvery === 0) spawnWave();",
      "",
      "  const sp = " + speed + " * dt;",
      "  if (display.keys[37] || display.keys[65]) player.x -= sp;",
      "  if (display.keys[39] || display.keys[68]) player.x += sp;",
      "  if (display.keys[38] || display.keys[87]) player.y -= sp;",
      "  if (display.keys[40] || display.keys[83]) player.y += sp;",
      "  if (player.x < 0) player.x = 0;",
      "  if (player.x + player.width > 800) player.x = 800 - player.width;",
      "  if (player.y < 80) player.y = 80;",
      "  if (player.y + player.height > 600) player.y = 600 - player.height;",
      "",
      "  const sp2 = 320 * dt;",
      "  const mx = display.x, my = display.y;",
      "  if (mx !== false && my !== false) {",
      "    player.x += (mx - 20 - player.x) * 8 * dt;",
      "    player.y += (my - 20 - player.y) * 8 * dt;",
      "  }",
      "",
      "  for (let i = blocks.length - 1; i >= 0; i--) {",
      "    const b = blocks[i];",
      "    b.x += b.vx || 0;",
      "    b.y += b.vy || 0;",
      "",
      "    if (b.x > 900 || b.x < -200 || b.y > 700 || b.y < -200) {",
      "      b.destroy();",
      "      blocks.splice(i, 1);",
      "      continue;",
      "    }",
      "",
      "    if (rectHit(player, b)) {",
      "      gameOver = true;",
      "      score.setText('Game Over! Survived: ' + timeAlive + 's');",
      "      showRestart();",
      "      return;",
      "    }",
      "  }",
      "}"
    ].join("\n");
  }
},
    tank: {
  name: "Tank Battle",
  fields: [
    { key: "title",  label: "Title",       type: "text",  default: "Tank Battle" },
    { key: "bg",     label: "Background",  type: "color", default: "#0d0d2a" },
    { key: "tank",   label: "Your tank",   type: "color", default: "#4af" },
    { key: "enemy",  label: "Enemy tank",  type: "color", default: "#f44" },
    { key: "wall",   label: "Walls",       type: "color", default: "#555555" },
    { key: "bullet", label: "Bullet",      type: "color", default: "#fd3" },
    { key: "speed",  label: "Move speed",  type: "text",  default: "320" },
    { key: "rate",   label: "Enemy spawn", type: "text",  default: "90" }
  ],
  config: function(cfg) {
    return {
      title: cfg.title,
      world: { w: 800, h: 600, bg: cfg.bg },
      slots: [
        { x: 375, y: 520, w: 50, h: 40, color: cfg.tank },
        { x: 200, y: 300, w: 40, h: 80, color: cfg.wall },
        { x: 375, y: 200, w: 50, h: 40, color: cfg.enemy }
      ],
      palette: [cfg.tank, cfg.enemy, cfg.wall, cfg.bullet]
    };
  },
  generate: function(cfg) {
    var speed = parseInt(cfg.speed) || 320;
    var rate = parseInt(cfg.rate) || 90;
    return [
      "const display = new Display();",
      "display.perform();",
      "display.start(800, 600);",
      "display.backgroundColor('" + cfg.bg + "');",
      "",
      "const player = new Component(50, 40, '" + cfg.tank + "', 375, 520, 'rect');",
      "display.add(player);",
      "",
      "const walls = [",
      "  new Component(40, 80, '" + cfg.wall + "', 180, 300, 'rect'),",
      "  new Component(40, 80, '" + cfg.wall + "', 580, 300, 'rect'),",
      "  new Component(180, 40, '" + cfg.wall + "', 310, 420, 'rect')",
      "];",
      "walls.forEach(function(w) { display.add(w); });",
      "",
      "const score = new Tctxt('20px','Arial','white',20,40,'left',false,'top','rgba(0,0,0,0.5)',10,4);",
      "score.setText('HP: 3  Score: 0');",
      "display.add(score);",
      "",
      "const btnL = new Component(80, 80, '#1a1a2e', 20, 500, 'rect');",
      "const btnR = new Component(80, 80, '#1a1a2e', 120, 500, 'rect');",
      "const btnF = new Component(120, 80, '#dc2626', 660, 500, 'rect');",
      "display.add(btnL); display.add(btnR); display.add(btnF);",
      "",
      "function inBtn(b, x, y) {",
      "  return x >= b.x && x <= b.x + b.width && y >= b.y && y <= b.y + b.height;",
      "}",
      "",
      "function rectHit(a, b) {",
      "  return a.x < b.x + b.width && a.x + a.width > b.x && a.y < b.y + b.height && a.y + a.height > b.y;",
      "}",
      "",
      "const pBullets = [];",
      "const eBullets = [];",
      "const enemies = [];",
      "let frame = 0;",
      "let points = 0;",
      "let hp = 3;",
      "let gameOver = false;",
      "let restartBtn = null;",
      "let restartLbl = null;",
      "",
      "function spawnEnemy() {",
      "  const e = new Component(50, 40, '" + cfg.enemy + "', 40 + Math.random() * 680, -40, 'rect');",
      "  e.dir = Math.random() < 0.5 ? -1 : 1;",
      "  e.shootTimer = 60 + Math.floor(Math.random() * 90);",
      "  display.add(e);",
      "  enemies.push(e);",
      "}",
      "",
      "function showRestart() {",
      "  restartBtn = new Component(220, 60, '#2563eb', 290, 280, 'rect');",
      "  restartLbl = new Tctxt('22px','Arial','white',400,310,'center',false,'middle');",
      "  restartLbl.setText('▶ PLAY AGAIN');",
      "  display.add(restartBtn); display.add(restartLbl);",
      "}",
      "",
      "function restart() {",
      "  if (restartBtn) { restartBtn.destroy(); restartBtn = null; }",
      "  if (restartLbl) { restartLbl.destroy(); restartLbl = null; }",
      "  for (const b of pBullets) b.destroy();",
      "  for (const b of eBullets) b.destroy();",
      "  for (const e of enemies) e.destroy();",
      "  pBullets.length = 0; eBullets.length = 0; enemies.length = 0;",
      "  player.x = 375; player.y = 520;",
      "  frame = 0; points = 0; hp = 3; gameOver = false;",
      "  score.setText('HP: 3  Score: 0');",
      "}",
      "",
      "function update(dt) {",
      "  if (gameOver) {",
      "    const mx = display.x, my = display.y;",
      "    if (mx !== false && restartBtn &&",
      "        mx >= restartBtn.x && mx <= restartBtn.x + restartBtn.width &&",
      "        my >= restartBtn.y && my <= restartBtn.y + restartBtn.height) restart();",
      "    return;",
      "  }",
      "",
      "  frame++;",
      "  if (frame % " + rate + " === 0) spawnEnemy();",
      "",
      "  const mx = display.x, my = display.y;",
      "  const sp = " + speed + " * dt;",
      "  if (display.keys[37] || display.keys[65] || (mx !== false && inBtn(btnL, mx, my))) player.x -= sp;",
      "  if (display.keys[39] || display.keys[68] || (mx !== false && inBtn(btnR, mx, my))) player.x += sp;",
      "  if (player.x < 0) player.x = 0;",
      "  if (player.x + player.width > 800) player.x = 800 - player.width;",
      "",
      "  const keyFire = display.keys[32] || display.keys[38];",
      "  const tapFire = mx !== false && inBtn(btnF, mx, my);",
      "  if ((keyFire || tapFire) && frame % 15 === 0) {",
      "    const b = new Component(6, 14, '" + cfg.bullet + "', player.x + 22, player.y - 10, 'rect');",
      "    display.add(b);",
      "    pBullets.push(b);",
      "  }",
      "",
      "  for (let i = pBullets.length - 1; i >= 0; i--) {",
      "    const b = pBullets[i];",
      "    b.y -= 10;",
      "    if (b.y < -20) { b.destroy(); pBullets.splice(i, 1); continue; }",
      "    for (const w of walls) {",
      "      if (rectHit(b, w)) { b.destroy(); pBullets.splice(i, 1); break; }",
      "    }",
      "  }",
      "",
      "  for (let i = eBullets.length - 1; i >= 0; i--) {",
      "    const b = eBullets[i];",
      "    b.y += 6;",
      "    if (b.y > 620) { b.destroy(); eBullets.splice(i, 1); continue; }",
      "    if (rectHit(player, b)) {",
      "      b.destroy(); eBullets.splice(i, 1);",
      "      hp--;",
      "      score.setText('HP: ' + hp + '  Score: ' + points);",
      "      if (hp <= 0) { gameOver = true; score.setText('Game Over! Score: ' + points); showRestart(); return; }",
      "    }",
      "  }",
      "",
      "  for (let i = enemies.length - 1; i >= 0; i--) {",
      "    const e = enemies[i];",
      "    e.y += 1.5; e.x += e.dir * 1.5;",
      "    if (e.x < 0 || e.x + e.width > 800) e.dir *= -1;",
      "    e.shootTimer--;",
      "    if (e.shootTimer <= 0) {",
      "      const b = new Component(6, 14, '" + cfg.bullet + "', e.x + 22, e.y + e.height, 'rect');",
      "      display.add(b); eBullets.push(b);",
      "      e.shootTimer = 90 + Math.floor(Math.random() * 60);",
      "    }",
      "    if (e.y > 620) { e.destroy(); enemies.splice(i, 1); continue; }",
      "    if (rectHit(player, e)) {",
      "      e.destroy(); enemies.splice(i, 1); hp -= 2;",
      "      score.setText('HP: ' + hp + '  Score: ' + points);",
      "      if (hp <= 0) { gameOver = true; score.setText('Game Over! Score: ' + points); showRestart(); return; }",
      "      continue;",
      "    }",
      "    for (let j = pBullets.length - 1; j >= 0; j--) {",
      "      if (rectHit(pBullets[j], e)) {",
      "        pBullets[j].destroy(); pBullets.splice(j, 1);",
      "        e.destroy(); enemies.splice(i, 1);",
      "        points += 20;",
      "        score.setText('HP: ' + hp + '  Score: ' + points);",
      "        break;",
      "      }",
      "    }",
      "  }",
      "}"
    ].join("\n");
  }
},

dungeon: {
  name: "Dungeon Crawler",
  fields: [
    { key: "title",  label: "Title",       type: "text",  default: "Dungeon Run" },
    { key: "bg",     label: "Floor",       type: "color", default: "#1a1020" },
    { key: "wall",   label: "Walls",       type: "color", default: "#4a3a5a" },
    { key: "player", label: "Player",      type: "color", default: "#4af" },
    { key: "enemy",  label: "Enemy",       type: "color", default: "#f44" },
    { key: "coin",   label: "Treasure",    type: "color", default: "#fd3" },
    { key: "exit",   label: "Exit",        type: "color", default: "#4f8" },
    { key: "speed",  label: "Move speed",  type: "text",  default: "220" }
  ],
  config: function(cfg) {
    return {
      title: cfg.title,
      world: { w: 800, h: 600, bg: cfg.bg },
      slots: [
        { x: 40, y: 520, w: 36, h: 36, color: cfg.player },
        { x: 350, y: 300, w: 32, h: 32, color: cfg.enemy },
        { x: 400, y: 200, w: 20, h: 20, color: cfg.coin },
        { x: 720, y: 30, w: 50, h: 50, color: cfg.exit }
      ],
      palette: [cfg.player, cfg.enemy, cfg.coin, cfg.exit, cfg.wall]
    };
  },
  generate: function(cfg) {
    var speed = parseInt(cfg.speed) || 220;
    return [
      "const display = new Display();",
      "display.perform();",
      "display.start(800, 600);",
      "display.backgroundColor('" + cfg.bg + "');",
      "",
      "const score = new Tctxt('20px','Arial','white',20,40,'left',false,'top','rgba(0,0,0,0.5)',10,4);",
      "score.setText('Treasure: 0  HP: 3');",
      "display.add(score);",
      "",
      "const walls = [",
      "  new Component(30, 400, '" + cfg.wall + "', 200, 100, 'rect'),",
      "  new Component(30, 400, '" + cfg.wall + "', 570, 100, 'rect'),",
      "  new Component(340, 30, '" + cfg.wall + "', 200, 100, 'rect'),",
      "  new Component(340, 30, '" + cfg.wall + "', 200, 470, 'rect'),",
      "  new Component(120, 30, '" + cfg.wall + "', 340, 300, 'rect')",
      "];",
      "walls.forEach(function(w) { display.add(w); });",
      "",
      "const exit = new Component(50, 50, '" + cfg.exit + "', 720, 30, 'rect');",
      "display.add(exit);",
      "",
      "const player = new Component(36, 36, '" + cfg.player + "', 40, 520, 'rect');",
      "player.changeAngle = false;",
      "display.add(player);",
      "",
      "const enemies = [];",
      "const coins = [];",
      "let frame = 0;",
      "let points = 0;",
      "let hp = 3;",
      "let invuln = 0;",
      "let gameOver = false;",
      "let won = false;",
      "let restartBtn = null;",
      "let restartLbl = null;",
      "",
      "function rectHit(a, b) {",
      "  return a.x < b.x + b.width && a.x + a.width > b.x && a.y < b.y + b.height && a.y + a.height > b.y;",
      "}",
      "",
      "function spawnEnemy(x, y) {",
      "  const e = new Component(32, 32, '" + cfg.enemy + "', x, y, 'rect');",
      "  e.changeAngle = false;",
      "  e.vx = (Math.random() < 0.5 ? -1 : 1) * (0.8 + Math.random() * 0.8);",
      "  e.vy = (Math.random() < 0.5 ? -1 : 1) * (0.8 + Math.random() * 0.8);",
      "  display.add(e); enemies.push(e);",
      "}",
      "",
      "function spawnCoin(x, y) {",
      "  const c = new Component(20, 20, '" + cfg.coin + "', x, y, 'rect');",
      "  c.changeAngle = false;",
      "  display.add(c); coins.push(c);",
      "}",
      "",
      "function initLevel() {",
      "  spawnEnemy(350, 300);",
      "  spawnEnemy(450, 380);",
      "  spawnCoin(300, 200);",
      "  spawnCoin(400, 400);",
      "  spawnCoin(500, 200);",
      "}",
      "",
      "function showRestart(msg) {",
      "  restartBtn = new Component(220, 60, '#2563eb', 290, 280, 'rect');",
      "  restartLbl = new Tctxt('22px','Arial','white',400,310,'center',false,'middle');",
      "  restartLbl.setText(msg);",
      "  display.add(restartBtn); display.add(restartLbl);",
      "}",
      "",
      "function restart() {",
      "  if (restartBtn) { restartBtn.destroy(); restartBtn = null; }",
      "  if (restartLbl) { restartLbl.destroy(); restartLbl = null; }",
      "  for (const e of enemies) e.destroy();",
      "  for (const c of coins) c.destroy();",
      "  enemies.length = 0; coins.length = 0;",
      "  player.x = 40; player.y = 520;",
      "  frame = 0; points = 0; hp = 3; invuln = 0;",
      "  gameOver = false; won = false;",
      "  score.setText('Treasure: 0  HP: 3');",
      "  initLevel();",
      "}",
      "",
      "const btnSize = 80;",
      "const btnUp    = new Component(btnSize, btnSize, '#1a1a2e', 360, 440, 'rect');",
      "const btnDown  = new Component(btnSize, btnSize, '#1a1a2e', 360, 540, 'rect');",
      "const btnLeft  = new Component(btnSize, btnSize, '#1a1a2e', 260, 490, 'rect');",
      "const btnRight = new Component(btnSize, btnSize, '#1a1a2e', 460, 490, 'rect');",
      "display.add(btnUp); display.add(btnDown); display.add(btnLeft); display.add(btnRight);",
      "",
      "function inBtn(b, x, y) {",
      "  return x >= b.x && x <= b.x + b.width && y >= b.y && y <= b.y + b.height;",
      "}",
      "",
      "initLevel();",
      "",
      "function update(dt) {",
      "  if (gameOver || won) {",
      "    const mx = display.x, my = display.y;",
      "    if (mx !== false && restartBtn &&",
      "        mx >= restartBtn.x && mx <= restartBtn.x + restartBtn.width &&",
      "        my >= restartBtn.y && my <= restartBtn.y + restartBtn.height) restart();",
      "    return;",
      "  }",
      "",
      "  frame++;",
      "  if (invuln > 0) invuln--;",
      "",
      "  const sp = " + speed + " * dt;",
      "  const mx = display.x, my = display.y;",
      "  let dx = 0, dy = 0;",
      "  if (display.keys[37] || display.keys[65] || (mx !== false && inBtn(btnLeft, mx, my))) dx -= 1;",
      "  if (display.keys[39] || display.keys[68] || (mx !== false && inBtn(btnRight, mx, my))) dx += 1;",
      "  if (display.keys[38] || display.keys[87] || (mx !== false && inBtn(btnUp, mx, my))) dy -= 1;",
      "  if (display.keys[40] || display.keys[83] || (mx !== false && inBtn(btnDown, mx, my))) dy += 1;",
      "  if (dx !== 0 && dy !== 0) { dx *= 0.707; dy *= 0.707; }",
      "",
      "  const oldX = player.x, oldY = player.y;",
      "  player.x += dx * sp; player.y += dy * sp;",
      "  for (const w of walls) { if (rectHit(player, w)) { player.x = oldX; player.y = oldY; } }",
      "",
      "  if (player.x < 0) player.x = 0;",
      "  if (player.x + player.width > 800) player.x = 800 - player.width;",
      "  if (player.y < 60) player.y = 60;",
      "  if (player.y + player.height > 600) player.y = 600 - player.height;",
      "",
      "  for (let i = coins.length - 1; i >= 0; i--) {",
      "    if (rectHit(player, coins[i])) {",
      "      coins[i].destroy(); coins.splice(i, 1);",
      "      points += 10;",
      "      score.setText('Treasure: ' + points + '  HP: ' + hp);",
      "    }",
      "  }",
      "",
      "  for (const e of enemies) {",
      "    e.x += e.vx; e.y += e.vy;",
      "    if (e.x < 0 || e.x + e.width > 800) e.vx *= -1;",
      "    if (e.y < 60 || e.y + e.height > 600) e.vy *= -1;",
      "    for (const w of walls) { if (rectHit(e, w)) { e.vx *= -1; e.vy *= -1; } }",
      "  }",
      "",
      "  if (invuln === 0) {",
      "    for (const e of enemies) {",
      "      if (rectHit(player, e)) {",
      "        hp--; invuln = 60;",
      "        score.setText('Treasure: ' + points + '  HP: ' + hp);",
      "        if (hp <= 0) { gameOver = true; score.setText('You died! Treasure: ' + points); showRestart('▶ TRY AGAIN'); return; }",
      "        break;",
      "      }",
      "    }",
      "  }",
      "",
      "  if (rectHit(player, exit)) {",
      "    won = true;",
      "    score.setText('You escaped! Treasure: ' + points);",
      "    showRestart('▶ PLAY AGAIN');",
      "  }",
      "}"
    ].join("\n");
  }
},

soccer: {
  name: "Soccer",
  fields: [
    { key: "title",  label: "Title",        type: "text",  default: "Soccer Showdown" },
    { key: "field",  label: "Field",        type: "color", default: "#0a3d0a" },
    { key: "line",   label: "Center line",  type: "color", default: "#ffffff" },
    { key: "player", label: "Your paddle",  type: "color", default: "#4af" },
    { key: "enemy",  label: "Opponent",     type: "color", default: "#f44" },
    { key: "ball",   label: "Ball",         type: "color", default: "#ffffff" },
    { key: "speed",  label: "Ball speed",   type: "text",  default: "6" },
    { key: "win",    label: "Score to win", type: "text",  default: "5" }
  ],
  config: function(cfg) {
    return {
      title: cfg.title,
      world: { w: 800, h: 600, bg: cfg.field },
      slots: [
        { x: 30, y: 250, w: 20, h: 100, color: cfg.player },
        { x: 750, y: 250, w: 20, h: 100, color: cfg.enemy },
        { x: 390, y: 290, w: 20, h: 20, color: cfg.ball }
      ],
      palette: [cfg.player, cfg.enemy, cfg.ball, cfg.line]
    };
  },
  generate: function(cfg) {
    var speed = parseInt(cfg.speed) || 6;
    var winScore = parseInt(cfg.win) || 5;
    return [
      "const display = new Display();",
      "display.perform();",
      "display.start(800, 600);",
      "display.backgroundColor('" + cfg.field + "');",
      "",
      "const line = new Component(4, 600, '" + cfg.line + "', 398, 0, 'rect');",
      "display.add(line);",
      "",
      "const player = new Component(20, 100, '" + cfg.player + "', 30, 250, 'rect');",
      "const enemy  = new Component(20, 100, '" + cfg.enemy + "', 750, 250, 'rect');",
      "display.add(player); display.add(enemy);",
      "",
      "const ball = new Component(20, 20, '" + cfg.ball + "', 390, 290, 'rect');",
      "ball.changeAngle = false;",
      "display.add(ball);",
      "",
      "let vx = " + speed + ", vy = " + speed + ";",
      "let pScore = 0, eScore = 0;",
      "let rally = 0;",
      "let gameOver = false;",
      "let restartBtn = null;",
      "let restartLbl = null;",
      "",
      "const score = new Tctxt('28px','Arial','white',400,40,'center',false,'top','rgba(0,0,0,0.5)',14,6);",
      "function updScore() { score.setText('YOU  ' + pScore + ' — ' + eScore + '  CPU'); }",
      "updScore(); display.add(score);",
      "",
      "function rectHit(a, b) {",
      "  return a.x < b.x + b.width && a.x + a.width > b.x && a.y < b.y + b.height && a.y + a.height > b.y;",
      "}",
      "",
      "function serve(dir) {",
      "  ball.x = 390; ball.y = 290;",
      "  vx = " + speed + " * dir; vy = " + speed + " * (Math.random() < 0.5 ? -1 : 1);",
      "  rally = 0;",
      "}",
      "",
      "function showRestart(msg) {",
      "  restartBtn = new Component(240, 60, '#2563eb', 280, 280, 'rect');",
      "  restartLbl = new Tctxt('22px','Arial','white',400,310,'center',false,'middle');",
      "  restartLbl.setText(msg);",
      "  display.add(restartBtn); display.add(restartLbl);",
      "}",
      "",
      "function restart() {",
      "  if (restartBtn) { restartBtn.destroy(); restartBtn = null; }",
      "  if (restartLbl) { restartLbl.destroy(); restartLbl = null; }",
      "  pScore = 0; eScore = 0; gameOver = false;",
      "  player.y = 250; enemy.y = 250;",
      "  updScore(); serve(1);",
      "}",
      "",
      "const btnUp   = new Component(80, 80, '#1a1a2e', 20, 440, 'rect');",
      "const btnDown = new Component(80, 80, '#1a1a2e', 20, 520, 'rect');",
      "display.add(btnUp); display.add(btnDown);",
      "",
      "function inBtn(b, x, y) {",
      "  return x >= b.x && x <= b.x + b.width && y >= b.y && y <= b.y + b.height;",
      "}",
      "",
      "const paddleSpeed = 420;",
      "",
      "function update(dt) {",
      "  if (gameOver) {",
      "    const mx = display.x, my = display.y;",
      "    if (mx !== false && restartBtn &&",
      "        mx >= restartBtn.x && mx <= restartBtn.x + restartBtn.width &&",
      "        my >= restartBtn.y && my <= restartBtn.y + restartBtn.height) restart();",
      "    return;",
      "  }",
      "",
      "  const mx = display.x, my = display.y;",
      "  const ps = paddleSpeed * dt;",
      "  if (display.keys[38] || display.keys[87] || (mx !== false && inBtn(btnUp, mx, my))) player.y -= ps;",
      "  if (display.keys[40] || display.keys[83] || (mx !== false && inBtn(btnDown, mx, my))) player.y += ps;",
      "  if (player.y < 0) player.y = 0;",
      "  if (player.y + player.height > 600) player.y = 600 - player.height;",
      "",
      "  const target = ball.y + 10 - enemy.height / 2;",
      "  enemy.y += Math.sign(target - enemy.y) * Math.min(ps, Math.abs(target - enemy.y));",
      "  if (enemy.y < 0) enemy.y = 0;",
      "  if (enemy.y + enemy.height > 600) enemy.y = 600 - enemy.height;",
      "",
      "  ball.x += vx; ball.y += vy; rally++;",
      "  const spd = Math.min(2, 1 + rally / 400);",
      "",
      "  if (ball.y <= 0 || ball.y + ball.height >= 600) vy = -vy;",
      "",
      "  if (rectHit(ball, player) && vx < 0) {",
      "    vx = Math.abs(vx) * spd;",
      "    vy += (ball.y - (player.y + player.height / 2)) * 0.15;",
      "  }",
      "  if (rectHit(ball, enemy) && vx > 0) {",
      "    vx = -Math.abs(vx) * spd;",
      "    vy += (ball.y - (enemy.y + enemy.height / 2)) * 0.15;",
      "  }",
      "  if (vy > 12) vy = 12;",
      "  if (vy < -12) vy = -12;",
      "",
      "  if (ball.x < -40) {",
      "    eScore++; updScore();",
      "    if (eScore >= " + winScore + ") { gameOver = true; score.setText('You lost ' + pScore + ' — ' + eScore); showRestart('▶ PLAY AGAIN'); return; }",
      "    serve(1);",
      "  } else if (ball.x > 840) {",
      "    pScore++; updScore();",
      "    if (pScore >= " + winScore + ") { gameOver = true; score.setText('You won ' + pScore + ' — ' + eScore); showRestart('▶ PLAY AGAIN'); return; }",
      "    serve(-1);",
      "  }",
      "}"
    ].join("\n");
  }
},

race: {
  name: "Car Race",
  fields: [
    { key: "title",  label: "Title",          type: "text",  default: "Turbo Road" },
    { key: "bg",     label: "Grass",          type: "color", default: "#1a4a1a" },
    { key: "road",   label: "Road",           type: "color", default: "#333333" },
    { key: "player", label: "Your car",       type: "color", default: "#4af" },
    { key: "enemy",  label: "Other cars",     type: "color", default: "#f44" },
    { key: "speed",  label: "Scroll speed",   type: "text",  default: "6" },
    { key: "spawn",  label: "Spawn (frames)", type: "text",  default: "70" }
  ],
  config: function(cfg) {
    return {
      title: cfg.title,
      world: { w: 800, h: 600, bg: cfg.bg },
      slots: [
        { x: 375, y: 480, w: 50, h: 80, color: cfg.player },
        { x: 250, y: 100, w: 50, h: 80, color: cfg.enemy }
      ],
      palette: [cfg.player, cfg.enemy, cfg.road]
    };
  },
  generate: function(cfg) {
    var speed = parseInt(cfg.speed) || 6;
    var spawnRate = parseInt(cfg.spawn) || 70;
    return [
      "const display = new Display();",
      "display.perform();",
      "display.start(800, 600);",
      "display.backgroundColor('" + cfg.bg + "');",
      "",
      "const road = new Component(500, 600, '" + cfg.road + "', 150, 0, 'rect');",
      "display.add(road);",
      "",
      "const lines = [];",
      "for (let i = 0; i < 6; i++) {",
      "  const l = new Component(6, 60, '#ffffff', 398, i * 110 - 60, 'rect');",
      "  display.add(l); lines.push(l);",
      "}",
      "",
      "const player = new Component(50, 80, '" + cfg.player + "', 375, 480, 'rect');",
      "player.changeAngle = false;",
      "display.add(player);",
      "",
      "const score = new Tctxt('20px','Arial','white',20,40,'left',false,'top','rgba(0,0,0,0.5)',10,4);",
      "score.setText('Score: 0');",
      "display.add(score);",
      "",
      "const cars = [];",
      "let frame = 0;",
      "let points = 0;",
      "let gameOver = false;",
      "let restartBtn = null;",
      "let restartLbl = null;",
      "",
      "function rectHit(a, b) {",
      "  return a.x < b.x + b.width && a.x + a.width > b.x && a.y < b.y + b.height && a.y + a.height > b.y;",
      "}",
      "",
      "function spawnCar() {",
      "  const lanes = [170, 260, 350, 440, 530];",
      "  const lane = lanes[Math.floor(Math.random() * lanes.length)];",
      "  const c = new Component(50, 80, '" + cfg.enemy + "', lane, -90, 'rect');",
      "  c.changeAngle = false;",
      "  display.add(c); cars.push(c);",
      "}",
      "",
      "function showRestart() {",
      "  restartBtn = new Component(220, 60, '#2563eb', 290, 280, 'rect');",
      "  restartLbl = new Tctxt('22px','Arial','white',400,310,'center',false,'middle');",
      "  restartLbl.setText('▶ PLAY AGAIN');",
      "  display.add(restartBtn); display.add(restartLbl);",
      "}",
      "",
      "function restart() {",
      "  if (restartBtn) { restartBtn.destroy(); restartBtn = null; }",
      "  if (restartLbl) { restartLbl.destroy(); restartLbl = null; }",
      "  for (const c of cars) c.destroy();",
      "  cars.length = 0;",
      "  player.x = 375;",
      "  frame = 0; points = 0; gameOver = false;",
      "  score.setText('Score: 0');",
      "}",
      "",
      "const btnL = new Component(90, 90, '#1a1a2e', 20, 490, 'rect');",
      "const btnR = new Component(90, 90, '#1a1a2e', 120, 490, 'rect');",
      "display.add(btnL); display.add(btnR);",
      "",
      "function inBtn(b, x, y) {",
      "  return x >= b.x && x <= b.x + b.width && y >= b.y && y <= b.y + b.height;",
      "}",
      "",
      "const steerSpeed = 420;",
      "",
      "function update(dt) {",
      "  if (gameOver) {",
      "    const mx = display.x, my = display.y;",
      "    if (mx !== false && restartBtn &&",
      "        mx >= restartBtn.x && mx <= restartBtn.x + restartBtn.width &&",
      "        my >= restartBtn.y && my <= restartBtn.y + restartBtn.height) restart();",
      "    return;",
      "  }",
      "",
      "  frame++;",
      "  if (frame % " + spawnRate + " === 0) spawnCar();",
      "",
      "  const mx = display.x, my = display.y;",
      "  const sp = steerSpeed * dt;",
      "  if (display.keys[37] || display.keys[65] || (mx !== false && inBtn(btnL, mx, my))) player.x -= sp;",
      "  if (display.keys[39] || display.keys[68] || (mx !== false && inBtn(btnR, mx, my))) player.x += sp;",
      "  if (player.x < 150) player.x = 150;",
      "  if (player.x + player.width > 650) player.x = 650 - player.width;",
      "",
      "  for (const l of lines) { l.y += " + speed + "; if (l.y > 660) l.y = -60; }",
      "",
      "  for (let i = cars.length - 1; i >= 0; i--) {",
      "    const c = cars[i];",
      "    c.y += " + speed + " + 2;",
      "    if (c.y > 660) {",
      "      c.destroy(); cars.splice(i, 1);",
      "      points += 5; score.setText('Score: ' + points);",
      "      continue;",
      "    }",
      "    if (rectHit(player, c)) {",
      "      gameOver = true;",
      "      score.setText('Crashed! Score: ' + points);",
      "      showRestart(); return;",
      "    }",
      "  }",
      "}"
    ].join("\n");
  }
},

asteroids: {
  name: "Asteroids",
  fields: [
    { key: "title",    label: "Title",          type: "text",  default: "Asteroids" },
    { key: "bg",       label: "Space",          type: "color", default: "#000000" },
    { key: "ship",     label: "Ship",           type: "color", default: "#4af" },
    { key: "asteroid", label: "Asteroid",       type: "color", default: "#888888" },
    { key: "bullet",   label: "Bullet",         type: "color", default: "#fd3" },
    { key: "thrust",   label: "Thrust power",   type: "text",  default: "0.2" },
    { key: "rot",      label: "Rotation speed", type: "text",  default: "3" }
  ],
  config: function(cfg) {
    return {
      title: cfg.title,
      world: { w: 800, h: 600, bg: cfg.bg },
      slots: [
        { x: 400, y: 300, w: 30, h: 30, color: cfg.ship },
        { x: 600, y: 200, w: 60, h: 60, color: cfg.asteroid }
      ],
      palette: [cfg.ship, cfg.asteroid, cfg.bullet]
    };
  },
  generate: function(cfg) {
    var thrustPower = parseFloat(cfg.thrust) || 0.2;
    var rotSpeed = parseFloat(cfg.rot) || 3;
    return [
      "const display = new Display();",
      "display.perform();",
      "display.start(800, 600);",
      "display.backgroundColor('" + cfg.bg + "');",
      "",
      "const ship = new Component(30, 30, '" + cfg.ship + "', 400, 300, 'rect');",
      "ship.changeAngle = true;",
      "ship.speedX = 0; ship.speedY = 0;",
      "display.add(ship);",
      "",
      "const score = new Tctxt('20px','Arial','white',20,40,'left',false,'top','rgba(0,0,0,0.5)',10,4);",
      "score.setText('Score: 0  Lives: 3');",
      "display.add(score);",
      "",
      "const asteroids = [];",
      "const bullets = [];",
      "let frame = 0;",
      "let points = 0;",
      "let lives = 3;",
      "let invuln = 0;",
      "let gameOver = false;",
      "let restartBtn = null;",
      "let restartLbl = null;",
      "",
      "function rectHit(a, b) {",
      "  return a.x < b.x + b.width && a.x + a.width > b.x && a.y < b.y + b.height && a.y + a.height > b.y;",
      "}",
      "",
      "function spawnAsteroid() {",
      "  const size = 40 + Math.floor(Math.random() * 40);",
      "  const edge = Math.floor(Math.random() * 4);",
      "  let x, y;",
      "  if (edge === 0) { x = Math.random() * 800; y = -size; }",
      "  else if (edge === 1) { x = 800 + size; y = Math.random() * 600; }",
      "  else if (edge === 2) { x = Math.random() * 800; y = 600 + size; }",
      "  else { x = -size; y = Math.random() * 600; }",
      "  const a = new Component(size, size, '" + cfg.asteroid + "', x, y, 'rect');",
      "  a.changeAngle = false;",
      "  const sp = 1 + Math.random() * 2;",
      "  const ang = Math.random() * Math.PI * 2;",
      "  a.vx = Math.cos(ang) * sp; a.vy = Math.sin(ang) * sp;",
      "  display.add(a); asteroids.push(a);",
      "}",
      "",
      "function showRestart() {",
      "  restartBtn = new Component(220, 60, '#2563eb', 290, 280, 'rect');",
      "  restartLbl = new Tctxt('22px','Arial','white',400,310,'center',false,'middle');",
      "  restartLbl.setText('▶ PLAY AGAIN');",
      "  display.add(restartBtn); display.add(restartLbl);",
      "}",
      "",
      "function restart() {",
      "  if (restartBtn) { restartBtn.destroy(); restartBtn = null; }",
      "  if (restartLbl) { restartLbl.destroy(); restartLbl = null; }",
      "  for (const a of asteroids) a.destroy();",
      "  for (const b of bullets) b.destroy();",
      "  asteroids.length = 0; bullets.length = 0;",
      "  ship.x = 400; ship.y = 300; ship.angle = 0; ship.speedX = 0; ship.speedY = 0;",
      "  frame = 0; points = 0; lives = 3; invuln = 0; gameOver = false;",
      "  score.setText('Score: 0  Lives: 3');",
      "}",
      "",
      "const btnRotL = new Component(80, 80, '#1a1a2e', 20, 490, 'rect');",
      "const btnRotR = new Component(80, 80, '#1a1a2e', 110, 490, 'rect');",
      "const btnThr  = new Component(80, 80, '#2563eb', 200, 490, 'rect');",
      "const btnFire = new Component(80, 80, '#dc2626', 680, 490, 'rect');",
      "display.add(btnRotL); display.add(btnRotR); display.add(btnThr); display.add(btnFire);",
      "",
      "function inBtn(b, x, y) {",
      "  return x >= b.x && x <= b.x + b.width && y >= b.y && y <= b.y + b.height;",
      "}",
      "",
      "const ROT = " + rotSpeed + ";",
      "const THRUST = " + thrustPower + ";",
      "",
      "function update(dt) {",
      "  if (gameOver) {",
      "    const mx = display.x, my = display.y;",
      "    if (mx !== false && restartBtn &&",
      "        mx >= restartBtn.x && mx <= restartBtn.x + restartBtn.width &&",
      "        my >= restartBtn.y && my <= restartBtn.y + restartBtn.height) restart();",
      "    return;",
      "  }",
      "",
      "  frame++;",
      "  if (frame % 100 === 0) spawnAsteroid();",
      "  if (invuln > 0) invuln--;",
      "",
      "  const mx = display.x, my = display.y;",
      "  const rot = ROT * 0.02;",
      "  if (display.keys[37] || display.keys[65] || (mx !== false && inBtn(btnRotL, mx, my))) ship.angle -= rot;",
      "  if (display.keys[39] || display.keys[68] || (mx !== false && inBtn(btnRotR, mx, my))) ship.angle += rot;",
      "",
      "  const thrusting = display.keys[38] || display.keys[87] || (mx !== false && inBtn(btnThr, mx, my));",
      "  if (thrusting) {",
      "    ship.speedX += Math.cos(ship.angle) * THRUST;",
      "    ship.speedY += Math.sin(ship.angle) * THRUST;",
      "  }",
      "",
      "  ship.speedX *= 0.99; ship.speedY *= 0.99;",
      "  ship.x += ship.speedX; ship.y += ship.speedY;",
      "",
      "  if (ship.x < -30) ship.x = 830;",
      "  if (ship.x > 830) ship.x = -30;",
      "  if (ship.y < -30) ship.y = 630;",
      "  if (ship.y > 630) ship.y = -30;",
      "",
      "  const firing = display.keys[32] || (mx !== false && inBtn(btnFire, mx, my));",
      "  if (firing && frame % 12 === 0) {",
      "    const b = new Component(6, 6, '" + cfg.bullet + "', ship.x + 12, ship.y + 12, 'rect');",
      "    b.changeAngle = false;",
      "    b.speedX = Math.cos(ship.angle) * 10;",
      "    b.speedY = Math.sin(ship.angle) * 10;",
      "    display.add(b); bullets.push(b);",
      "  }",
      "",
      "  for (let i = bullets.length - 1; i >= 0; i--) {",
      "    const b = bullets[i];",
      "    b.x += b.speedX; b.y += b.speedY;",
      "    if (b.x < -20 || b.x > 820 || b.y < -20 || b.y > 620) {",
      "      b.destroy(); bullets.splice(i, 1);",
      "    }",
      "  }",
      "",
      "  for (let i = asteroids.length - 1; i >= 0; i--) {",
      "    const a = asteroids[i];",
      "    a.x += a.vx; a.y += a.vy;",
      "",
      "    if (a.x < -80) a.x = 880;",
      "    if (a.x > 880) a.x = -80;",
      "    if (a.y < -80) a.y = 680;",
      "    if (a.y > 680) a.y = -80;",
      "",
      "    for (let j = bullets.length - 1; j >= 0; j--) {",
      "      if (rectHit(bullets[j], a)) {",
      "        bullets[j].destroy(); bullets.splice(j, 1);",
      "        a.destroy(); asteroids.splice(i, 1);",
      "        points += 20;",
      "        score.setText('Score: ' + points + '  Lives: ' + lives);",
      "        break;",
      "      }",
      "    }",
      "",
      "    if (invuln === 0 && rectHit(ship, a)) {",
      "      lives--; invuln = 90;",
      "      ship.x = 400; ship.y = 300;",
      "      ship.speedX = 0; ship.speedY = 0;",
      "      score.setText('Score: ' + points + '  Lives: ' + lives);",
      "      if (lives <= 0) {",
      "        gameOver = true;",
      "        score.setText('Game Over! Score: ' + points);",
      "        showRestart(); return;",
      "      }",
      "    }",
      "  }",
      "}"
    ].join("\n");
  }
},
};
